"""
Mega Knowledge Base — thousands of structured facts for general knowledge.

Data-driven: countries, capitals, elements, planets, US states, geography
records, famous people, historical events, science constants, and more.

This module plugs into GeneralIntelligence via the same KnowledgeEntry
format used by knowledge_training.py.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class MegaEntry:
    """A single knowledge entry."""
    id: str
    domain: str
    topic: str
    fact: str
    answer: str
    confidence: float
    source: str = "mega_kb"
    category: str = "fact"


class MegaKnowledge:
    """Programmatically generated mega knowledge base."""

    def __init__(self) -> None:
        self._entries: list[MegaEntry] = []
        self._load_countries()
        self._load_elements()
        self._load_us_states()
        self._load_planets()
        self._load_geography_records()
        self._load_people()
        self._load_history()
        self._load_science_constants()
        self._load_math()
        self._load_computing()
        self._load_biology_health()
        self._load_misc()
        self._load_qa_records()

    def get_all(self) -> list[MegaEntry]:
        return self._entries

    def _add(self, domain: str, topic: str, answer: str, cat: str = "fact",
             conf: float = 0.97, fact: str | None = None) -> None:
        e = MegaEntry(
            id=f"mega_{len(self._entries)}",
            domain=domain,
            topic=topic,
            fact=fact or f"{topic}: {answer}",
            answer=answer,
            confidence=conf,
            category=cat,
        )
        self._entries.append(e)

    # ══════════════════════════════════════════════════════════
    # COUNTRIES — capital, continent, currency
    # ══════════════════════════════════════════════════════════
    def _load_countries(self) -> None:
        # (country, capital, continent, currency)
        countries = [
            ("Afghanistan", "Kabul", "Asia", "Afghan afghani"),
            ("Albania", "Tirana", "Europe", "Lek"),
            ("Algeria", "Algiers", "Africa", "Algerian dinar"),
            ("Andorra", "Andorra la Vella", "Europe", "Euro"),
            ("Angola", "Luanda", "Africa", "Kwanza"),
            ("Antigua and Barbuda", "Saint John's", "North America", "East Caribbean dollar"),
            ("Argentina", "Buenos Aires", "South America", "Argentine peso"),
            ("Armenia", "Yerevan", "Asia", "Armenian dram"),
            ("Australia", "Canberra", "Oceania", "Australian dollar"),
            ("Austria", "Vienna", "Europe", "Euro"),
            ("Azerbaijan", "Baku", "Asia", "Azerbaijani manat"),
            ("Bahamas", "Nassau", "North America", "Bahamian dollar"),
            ("Bahrain", "Manama", "Asia", "Bahraini dinar"),
            ("Bangladesh", "Dhaka", "Asia", "Bangladeshi taka"),
            ("Barbados", "Bridgetown", "North America", "Barbadian dollar"),
            ("Belarus", "Minsk", "Europe", "Belarusian ruble"),
            ("Belgium", "Brussels", "Europe", "Euro"),
            ("Belize", "Belmopan", "North America", "Belize dollar"),
            ("Benin", "Porto-Novo", "Africa", "West African CFA franc"),
            ("Bhutan", "Thimphu", "Asia", "Bhutanese ngultrum"),
            ("Bolivia", "Sucre", "South America", "Bolivian boliviano"),
            ("Bosnia and Herzegovina", "Sarajevo", "Europe", "Convertible mark"),
            ("Botswana", "Gaborone", "Africa", "Botswana pula"),
            ("Brazil", "Brasilia", "South America", "Brazilian real"),
            ("Brunei", "Bandar Seri Begawan", "Asia", "Brunei dollar"),
            ("Bulgaria", "Sofia", "Europe", "Bulgarian lev"),
            ("Burkina Faso", "Ouagadougou", "Africa", "West African CFA franc"),
            ("Burundi", "Gitega", "Africa", "Burundian franc"),
            ("Cambodia", "Phnom Penh", "Asia", "Cambodian riel"),
            ("Cameroon", "Yaounde", "Africa", "Central African CFA franc"),
            ("Canada", "Ottawa", "North America", "Canadian dollar"),
            ("Cape Verde", "Praia", "Africa", "Cape Verdean escudo"),
            ("Central African Republic", "Bangui", "Africa", "Central African CFA franc"),
            ("Chad", "N'Djamena", "Africa", "Central African CFA franc"),
            ("Chile", "Santiago", "South America", "Chilean peso"),
            ("China", "Beijing", "Asia", "Renminbi (Yuan)"),
            ("Colombia", "Bogota", "South America", "Colombian peso"),
            ("Comoros", "Moroni", "Africa", "Comorian franc"),
            ("Congo, Democratic Republic of the", "Kinshasa", "Africa", "Congolese franc"),
            ("Congo, Republic of the", "Brazzaville", "Africa", "Central African CFA franc"),
            ("Costa Rica", "San Jose", "North America", "Costa Rican colon"),
            ("Cote d'Ivoire", "Yamoussoukro", "Africa", "West African CFA franc"),
            ("Croatia", "Zagreb", "Europe", "Euro"),
            ("Cuba", "Havana", "North America", "Cuban peso"),
            ("Cyprus", "Nicosia", "Europe", "Euro"),
            ("Czech Republic", "Prague", "Europe", "Czech koruna"),
            ("Denmark", "Copenhagen", "Europe", "Danish krone"),
            ("Djibouti", "Djibouti City", "Africa", "Djiboutian franc"),
            ("Dominica", "Roseau", "North America", "East Caribbean dollar"),
            ("Dominican Republic", "Santo Domingo", "North America", "Dominican peso"),
            ("Ecuador", "Quito", "South America", "US dollar"),
            ("Egypt", "Cairo", "Africa", "Egyptian pound"),
            ("El Salvador", "San Salvador", "North America", "US dollar"),
            ("Equatorial Guinea", "Malabo", "Africa", "Central African CFA franc"),
            ("Eritrea", "Asmara", "Africa", "Eritrean nakfa"),
            ("Estonia", "Tallinn", "Europe", "Euro"),
            ("Eswatini", "Mbabane", "Africa", "Lilangeni"),
            ("Ethiopia", "Addis Ababa", "Africa", "Ethiopian birr"),
            ("Fiji", "Suva", "Oceania", "Fijian dollar"),
            ("Finland", "Helsinki", "Europe", "Euro"),
            ("France", "Paris", "Europe", "Euro"),
            ("Gabon", "Libreville", "Africa", "Central African CFA franc"),
            ("Gambia", "Banjul", "Africa", "Gambian dalasi"),
            ("Georgia", "Tbilisi", "Asia", "Georgian lari"),
            ("Germany", "Berlin", "Europe", "Euro"),
            ("Ghana", "Accra", "Africa", "Ghanaian cedi"),
            ("Greece", "Athens", "Europe", "Euro"),
            ("Grenada", "St. George's", "North America", "East Caribbean dollar"),
            ("Guatemala", "Guatemala City", "North America", "Guatemalan quetzal"),
            ("Guinea", "Conakry", "Africa", "Guinean franc"),
            ("Guinea-Bissau", "Bissau", "Africa", "West African CFA franc"),
            ("Guyana", "Georgetown", "South America", "Guyanese dollar"),
            ("Haiti", "Port-au-Prince", "North America", "Haitian gourde"),
            ("Honduras", "Tegucigalpa", "North America", "Honduran lempira"),
            ("Hungary", "Budapest", "Europe", "Hungarian forint"),
            ("Iceland", "Reykjavik", "Europe", "Icelandic krona"),
            ("India", "New Delhi", "Asia", "Indian rupee"),
            ("Indonesia", "Jakarta", "Asia", "Indonesian rupiah"),
            ("Iran", "Tehran", "Asia", "Iranian rial"),
            ("Iraq", "Baghdad", "Asia", "Iraqi dinar"),
            ("Ireland", "Dublin", "Europe", "Euro"),
            ("Israel", "Jerusalem", "Asia", "Israeli new shekel"),
            ("Italy", "Rome", "Europe", "Euro"),
            ("Jamaica", "Kingston", "North America", "Jamaican dollar"),
            ("Japan", "Tokyo", "Asia", "Japanese yen"),
            ("Jordan", "Amman", "Asia", "Jordanian dinar"),
            ("Kazakhstan", "Astana", "Asia", "Kazakhstani tenge"),
            ("Kenya", "Nairobi", "Africa", "Kenyan shilling"),
            ("Kiribati", "Tarawa", "Oceania", "Australian dollar"),
            ("Kuwait", "Kuwait City", "Asia", "Kuwaiti dinar"),
            ("Kyrgyzstan", "Bishkek", "Asia", "Kyrgyzstani som"),
            ("Laos", "Vientiane", "Asia", "Lao kip"),
            ("Latvia", "Riga", "Europe", "Euro"),
            ("Lebanon", "Beirut", "Asia", "Lebanese pound"),
            ("Lesotho", "Maseru", "Africa", "Lesotho loti"),
            ("Liberia", "Monrovia", "Africa", "Liberian dollar"),
            ("Libya", "Tripoli", "Africa", "Libyan dinar"),
            ("Liechtenstein", "Vaduz", "Europe", "Swiss franc"),
            ("Lithuania", "Vilnius", "Europe", "Euro"),
            ("Luxembourg", "Luxembourg City", "Europe", "Euro"),
            ("Madagascar", "Antananarivo", "Africa", "Malagasy ariary"),
            ("Malawi", "Lilongwe", "Africa", "Malawian kwacha"),
            ("Malaysia", "Kuala Lumpur", "Asia", "Malaysian ringgit"),
            ("Maldives", "Male", "Asia", "Maldivian rufiyaa"),
            ("Mali", "Bamako", "Africa", "West African CFA franc"),
            ("Malta", "Valletta", "Europe", "Euro"),
            ("Marshall Islands", "Majuro", "Oceania", "US dollar"),
            ("Mauritania", "Nouakchott", "Africa", "Mauritanian ouguiya"),
            ("Mauritius", "Port Louis", "Africa", "Mauritian rupee"),
            ("Mexico", "Mexico City", "North America", "Mexican peso"),
            ("Micronesia", "Palikir", "Oceania", "US dollar"),
            ("Moldova", "Chisinau", "Europe", "Moldovan leu"),
            ("Monaco", "Monaco", "Europe", "Euro"),
            ("Mongolia", "Ulaanbaatar", "Asia", "Mongolian tugrik"),
            ("Montenegro", "Podgorica", "Europe", "Euro"),
            ("Morocco", "Rabat", "Africa", "Moroccan dirham"),
            ("Mozambique", "Maputo", "Africa", "Mozambican metical"),
            ("Myanmar", "Naypyidaw", "Asia", "Burmese kyat"),
            ("Namibia", "Windhoek", "Africa", "Namibian dollar"),
            ("Nauru", "Yaren", "Oceania", "Australian dollar"),
            ("Nepal", "Kathmandu", "Asia", "Nepalese rupee"),
            ("Netherlands", "Amsterdam", "Europe", "Euro"),
            ("New Zealand", "Wellington", "Oceania", "New Zealand dollar"),
            ("Nicaragua", "Managua", "North America", "Nicaraguan cordoba"),
            ("Niger", "Niamey", "Africa", "West African CFA franc"),
            ("Nigeria", "Abuja", "Africa", "Nigerian naira"),
            ("North Korea", "Pyongyang", "Asia", "North Korean won"),
            ("North Macedonia", "Skopje", "Europe", "Macedonian denar"),
            ("Norway", "Oslo", "Europe", "Norwegian krone"),
            ("Oman", "Muscat", "Asia", "Omani rial"),
            ("Pakistan", "Islamabad", "Asia", "Pakistani rupee"),
            ("Palau", "Ngerulmud", "Oceania", "US dollar"),
            ("Palestine", "Ramallah", "Asia", "Israeli new shekel"),
            ("Panama", "Panama City", "North America", "Panamanian balboa"),
            ("Papua New Guinea", "Port Moresby", "Oceania", "Papua New Guinean kina"),
            ("Paraguay", "Asuncion", "South America", "Paraguayan guarani"),
            ("Peru", "Lima", "South America", "Peruvian sol"),
            ("Philippines", "Manila", "Asia", "Philippine peso"),
            ("Poland", "Warsaw", "Europe", "Polish zloty"),
            ("Portugal", "Lisbon", "Europe", "Euro"),
            ("Qatar", "Doha", "Asia", "Qatari riyal"),
            ("Romania", "Bucharest", "Europe", "Romanian leu"),
            ("Russia", "Moscow", "Europe", "Russian ruble"),
            ("Rwanda", "Kigali", "Africa", "Rwandan franc"),
            ("Saint Kitts and Nevis", "Basseterre", "North America", "East Caribbean dollar"),
            ("Saint Lucia", "Castries", "North America", "East Caribbean dollar"),
            ("Saint Vincent and the Grenadines", "Kingstown", "North America", "East Caribbean dollar"),
            ("Samoa", "Apia", "Oceania", "Samoan tala"),
            ("San Marino", "San Marino", "Europe", "Euro"),
            ("Sao Tome and Principe", "Sao Tome", "Africa", "Sao Tomean dobra"),
            ("Saudi Arabia", "Riyadh", "Asia", "Saudi riyal"),
            ("Senegal", "Dakar", "Africa", "West African CFA franc"),
            ("Serbia", "Belgrade", "Europe", "Serbian dinar"),
            ("Seychelles", "Victoria", "Africa", "Seychellois rupee"),
            ("Sierra Leone", "Freetown", "Africa", "Sierra Leonean leone"),
            ("Singapore", "Singapore", "Asia", "Singapore dollar"),
            ("Slovakia", "Bratislava", "Europe", "Euro"),
            ("Slovenia", "Ljubljana", "Europe", "Euro"),
            ("Solomon Islands", "Honiara", "Oceania", "Solomon Islands dollar"),
            ("Somalia", "Mogadishu", "Africa", "Somali shilling"),
            ("South Africa", "Pretoria", "Africa", "South African rand"),
            ("South Korea", "Seoul", "Asia", "South Korean won"),
            ("South Sudan", "Juba", "Africa", "South Sudanese pound"),
            ("Spain", "Madrid", "Europe", "Euro"),
            ("Sri Lanka", "Sri Jayawardenepura Kotte", "Asia", "Sri Lankan rupee"),
            ("Sudan", "Khartoum", "Africa", "Sudanese pound"),
            ("Suriname", "Paramaribo", "South America", "Surinamese dollar"),
            ("Sweden", "Stockholm", "Europe", "Swedish krona"),
            ("Switzerland", "Bern", "Europe", "Swiss franc"),
            ("Syria", "Damascus", "Asia", "Syrian pound"),
            ("Taiwan", "Taipei", "Asia", "New Taiwan dollar"),
            ("Tajikistan", "Dushanbe", "Asia", "Tajikistani somoni"),
            ("Tanzania", "Dodoma", "Africa", "Tanzanian shilling"),
            ("Thailand", "Bangkok", "Asia", "Thai baht"),
            ("Timor-Leste", "Dili", "Asia", "US dollar"),
            ("Togo", "Lome", "Africa", "West African CFA franc"),
            ("Tonga", "Nuku'alofa", "Oceania", "Tongan paanga"),
            ("Trinidad and Tobago", "Port of Spain", "North America", "Trinidad and Tobago dollar"),
            ("Tunisia", "Tunis", "Africa", "Tunisian dinar"),
            ("Turkey", "Ankara", "Asia", "Turkish lira"),
            ("Turkmenistan", "Ashgabat", "Asia", "Turkmenistani manat"),
            ("Tuvalu", "Funafuti", "Oceania", "Australian dollar"),
            ("Uganda", "Kampala", "Africa", "Ugandan shilling"),
            ("Ukraine", "Kyiv", "Europe", "Ukrainian hryvnia"),
            ("United Arab Emirates", "Abu Dhabi", "Asia", "UAE dirham"),
            ("United Kingdom", "London", "Europe", "Pound sterling"),
            ("United States", "Washington, D.C.", "North America", "US dollar"),
            ("Uruguay", "Montevideo", "South America", "Uruguayan peso"),
            ("Uzbekistan", "Tashkent", "Asia", "Uzbekistani som"),
            ("Vanuatu", "Port Vila", "Oceania", "Vanuatu vatu"),
            ("Vatican City", "Vatican City", "Europe", "Euro"),
            ("Venezuela", "Caracas", "South America", "Venezuelan bolivar"),
            ("Vietnam", "Hanoi", "Asia", "Vietnamese dong"),
            ("Yemen", "Sanaa", "Asia", "Yemeni rial"),
            ("Zambia", "Lusaka", "Africa", "Zambian kwacha"),
            ("Zimbabwe", "Harare", "Africa", "Zimbabwean dollar"),
        ]
        for country, capital, continent, currency in countries:
            self._add("geography", f"capital of {country}", capital, "fact")
            self._add("geography", f"{country} continent", continent, "fact")
            self._add("geography", f"{country} currency", currency, "fact")
            self._add("geography", f"{country} capital city", capital, "fact")

    # ══════════════════════════════════════════════════════════
    # CHEMICAL ELEMENTS
    # ══════════════════════════════════════════════════════════
    def _load_elements(self) -> None:
        elements = [
            ("Hydrogen", "H", 1), ("Helium", "He", 2), ("Lithium", "Li", 3),
            ("Beryllium", "Be", 4), ("Boron", "B", 5), ("Carbon", "C", 6),
            ("Nitrogen", "N", 7), ("Oxygen", "O", 8), ("Fluorine", "F", 9),
            ("Neon", "Ne", 10), ("Sodium", "Na", 11), ("Magnesium", "Mg", 12),
            ("Aluminum", "Al", 13), ("Silicon", "Si", 14), ("Phosphorus", "P", 15),
            ("Sulfur", "S", 16), ("Chlorine", "Cl", 17), ("Argon", "Ar", 18),
            ("Potassium", "K", 19), ("Calcium", "Ca", 20), ("Scandium", "Sc", 21),
            ("Titanium", "Ti", 22), ("Vanadium", "V", 23), ("Chromium", "Cr", 24),
            ("Manganese", "Mn", 25), ("Iron", "Fe", 26), ("Cobalt", "Co", 27),
            ("Nickel", "Ni", 28), ("Copper", "Cu", 29), ("Zinc", "Zn", 30),
            ("Gallium", "Ga", 31), ("Germanium", "Ge", 32), ("Arsenic", "As", 33),
            ("Selenium", "Se", 34), ("Bromine", "Br", 35), ("Krypton", "Kr", 36),
            ("Rubidium", "Rb", 37), ("Strontium", "Sr", 38), ("Yttrium", "Y", 39),
            ("Zirconium", "Zr", 40), ("Niobium", "Nb", 41), ("Molybdenum", "Mo", 42),
            ("Technetium", "Tc", 43), ("Ruthenium", "Ru", 44), ("Rhodium", "Rh", 45),
            ("Palladium", "Pd", 46), ("Silver", "Ag", 47), ("Cadmium", "Cd", 48),
            ("Indium", "In", 49), ("Tin", "Sn", 50), ("Antimony", "Sb", 51),
            ("Tellurium", "Te", 52), ("Iodine", "I", 53), ("Xenon", "Xe", 54),
            ("Cesium", "Cs", 55), ("Barium", "Ba", 56), ("Lanthanum", "La", 57),
            ("Cerium", "Ce", 58), ("Praseodymium", "Pr", 59), ("Neodymium", "Nd", 60),
            ("Promethium", "Pm", 61), ("Samarium", "Sm", 62), ("Europium", "Eu", 63),
            ("Gadolinium", "Gd", 64), ("Terbium", "Tb", 65), ("Dysprosium", "Dy", 66),
            ("Holmium", "Ho", 67), ("Erbium", "Er", 68), ("Thulium", "Tm", 69),
            ("Ytterbium", "Yb", 70), ("Lutetium", "Lu", 71), ("Hafnium", "Hf", 72),
            ("Tantalum", "Ta", 73), ("Tungsten", "W", 74), ("Rhenium", "Re", 75),
            ("Osmium", "Os", 76), ("Iridium", "Ir", 77), ("Platinum", "Pt", 78),
            ("Gold", "Au", 79), ("Mercury", "Hg", 80), ("Thallium", "Tl", 81),
            ("Lead", "Pb", 82), ("Bismuth", "Bi", 83), ("Polonium", "Po", 84),
            ("Astatine", "At", 85), ("Radon", "Rn", 86), ("Francium", "Fr", 87),
            ("Radium", "Ra", 88), ("Actinium", "Ac", 89), ("Thorium", "Th", 90),
            ("Protactinium", "Pa", 91), ("Uranium", "U", 92), ("Neptunium", "Np", 93),
            ("Plutonium", "Pu", 94), ("Americium", "Am", 95), ("Curium", "Cm", 96),
            ("Berkelium", "Bk", 97), ("Californium", "Cf", 98), ("Einsteinium", "Es", 99),
            ("Fermium", "Fm", 100), ("Mendelevium", "Md", 101), ("Nobelium", "No", 102),
            ("Lawrencium", "Lr", 103), ("Rutherfordium", "Rf", 104), ("Dubnium", "Db", 105),
            ("Seaborgium", "Sg", 106), ("Bohrium", "Bh", 107), ("Hassium", "Hs", 108),
            ("Meitnerium", "Mt", 109), ("Darmstadtium", "Ds", 110), ("Roentgenium", "Rg", 111),
            ("Copernicium", "Cn", 112), ("Nihonium", "Nh", 113), ("Flerovium", "Fl", 114),
            ("Moscovium", "Mc", 115), ("Livermorium", "Lv", 116), ("Tennessine", "Ts", 117),
            ("Oganesson", "Og", 118),
        ]
        for name, symbol, num in elements:
            self._add("chemistry", f"{name} symbol", symbol, "fact")
            self._add("chemistry", f"{name} atomic number", str(num), "fact")
            self._add("chemistry", f"symbol {symbol} element", name, "fact")
            self._add("chemistry", f"element number {num}", name, "fact")

    # ══════════════════════════════════════════════════════════
    # US STATES + CAPITALS
    # ══════════════════════════════════════════════════════════
    def _load_us_states(self) -> None:
        states = [
            ("Alabama", "Montgomery"), ("Alaska", "Juneau"), ("Arizona", "Phoenix"),
            ("Arkansas", "Little Rock"), ("California", "Sacramento"), ("Colorado", "Denver"),
            ("Connecticut", "Hartford"), ("Delaware", "Dover"), ("Florida", "Tallahassee"),
            ("Georgia", "Atlanta"), ("Hawaii", "Honolulu"), ("Idaho", "Boise"),
            ("Illinois", "Springfield"), ("Indiana", "Indianapolis"), ("Iowa", "Des Moines"),
            ("Kansas", "Topeka"), ("Kentucky", "Frankfort"), ("Louisiana", "Baton Rouge"),
            ("Maine", "Augusta"), ("Maryland", "Annapolis"), ("Massachusetts", "Boston"),
            ("Michigan", "Lansing"), ("Minnesota", "Saint Paul"), ("Mississippi", "Jackson"),
            ("Missouri", "Jefferson City"), ("Montana", "Helena"), ("Nebraska", "Lincoln"),
            ("Nevada", "Carson City"), ("New Hampshire", "Concord"), ("New Jersey", "Trenton"),
            ("New Mexico", "Santa Fe"), ("New York", "Albany"), ("North Carolina", "Raleigh"),
            ("North Dakota", "Bismarck"), ("Ohio", "Columbus"), ("Oklahoma", "Oklahoma City"),
            ("Oregon", "Salem"), ("Pennsylvania", "Harrisburg"), ("Rhode Island", "Providence"),
            ("South Carolina", "Columbia"), ("South Dakota", "Pierre"), ("Tennessee", "Nashville"),
            ("Texas", "Austin"), ("Utah", "Salt Lake City"), ("Vermont", "Montpelier"),
            ("Virginia", "Richmond"), ("Washington", "Olympia"), ("West Virginia", "Charleston"),
            ("Wisconsin", "Madison"), ("Wyoming", "Cheyenne"),
        ]
        for state, capital in states:
            self._add("geography", f"capital of {state}", capital, "fact")
            self._add("geography", f"{state} state capital", capital, "fact")

    # ══════════════════════════════════════════════════════════
    # PLANETS + SOLAR SYSTEM
    # ══════════════════════════════════════════════════════════
    def _load_planets(self) -> None:
        planets = [
            ("Mercury", 1, "0 moons", "smallest", 4879),
            ("Venus", 2, "0 moons", "hottest", 12104),
            ("Earth", 3, "1 moon", "densest", 12756),
            ("Mars", 4, "2 moons", "red", 6792),
            ("Jupiter", 5, "95 moons", "largest", 142984),
            ("Saturn", 6, "146 moons", "rings", 120536),
            ("Uranus", 7, "27 moons", "ice giant", 51118),
            ("Neptune", 8, "14 moons", "windiest", 49528),
        ]
        for name, pos, moons, note, diam in planets:
            self._add("astronomy", f"{name} position from sun", str(pos), "fact")
            self._add("astronomy", f"{name} moons", moons, "fact")
            self._add("astronomy", f"{name} diameter", f"{diam} km", "fact")
        self._add("astronomy", "largest planet", "Jupiter", "record")
        self._add("astronomy", "smallest planet", "Mercury", "record")
        self._add("astronomy", "hottest planet", "Venus", "record")
        self._add("astronomy", "closest planet to sun", "Mercury", "record")
        self._add("astronomy", "planet with most moons", "Saturn", "record")
        self._add("astronomy", "red planet", "Mars", "record")
        self._add("astronomy", "number of planets in solar system", "8", "fact")
        self._add("astronomy", "distance from earth to sun", "about 150 million km (1 AU)", "fact")
        self._add("astronomy", "how long earth takes to orbit sun", "365.25 days (1 year)", "fact")
        self._add("astronomy", "how long earth takes to rotate", "24 hours (1 day)", "fact")

    # ══════════════════════════════════════════════════════════
    # GEOGRAPHY RECORDS
    # ══════════════════════════════════════════════════════════
    def _load_geography_records(self) -> None:
        records = [
            ("largest ocean", "Pacific Ocean"),
            ("largest continent", "Asia"),
            ("smallest continent", "Australia"),
            ("largest country by area", "Russia"),
            ("largest country by population", "India"),
            ("smallest country", "Vatican City"),
            ("tallest mountain", "Mount Everest (8,849 m)"),
            ("longest river", "Nile (6,650 km)"),
            ("largest desert", "Antarctic Desert"),
            ("largest hot desert", "Sahara Desert"),
            ("largest rainforest", "Amazon Rainforest"),
            ("largest island", "Greenland"),
            ("largest lake", "Caspian Sea"),
            ("deepest lake", "Lake Baikal"),
            ("deepest ocean", "Pacific Ocean"),
            ("deepest point on earth", "Mariana Trench"),
            ("largest waterfall by volume", "Angel Falls"),
            ("largest city by population", "Tokyo"),
            ("highest capital city", "La Paz, Bolivia"),
            ("most populous country", "India"),
            ("largest country in Africa", "Algeria"),
            ("largest country in South America", "Brazil"),
            ("largest country in North America", "Canada"),
            ("longest mountain range", "Andes"),
            ("largest coral reef", "Great Barrier Reef"),
            ("most spoken language in the world", "Mandarin Chinese"),
            ("most widely spoken language", "English"),
            ("official language of Brazil", "Portuguese"),
            ("official language of India", "Hindi"),
            ("official language of Japan", "Japanese"),
            ("number of continents", "7"),
            ("number of oceans", "5"),
        ]
        for topic, answer in records:
            self._add("geography", topic, answer, "record")

    # ══════════════════════════════════════════════════════════
    # FAMOUS PEOPLE
    # ══════════════════════════════════════════════════════════
    def _load_people(self) -> None:
        people = [
            ("Albert Einstein", "physicist who developed the theory of relativity", "Germany"),
            ("Isaac Newton", "physicist who formulated laws of motion and gravity", "England"),
            ("Charles Darwin", "naturalist who proposed evolution by natural selection", "England"),
            ("Marie Curie", "physicist who pioneered radioactivity research", "Poland/France"),
            ("Leonardo da Vinci", "Renaissance polymath, painter of the Mona Lisa", "Italy"),
            ("William Shakespeare", "playwright and poet, author of Hamlet and Romeo and Juliet", "England"),
            ("Wolfgang Amadeus Mozart", "composer of classical music", "Austria"),
            ("Ludwig van Beethoven", "composer and pianist", "Germany"),
            ("Napoleon Bonaparte", "French military leader and emperor", "France"),
            ("George Washington", "first president of the United States", "United States"),
            ("Abraham Lincoln", "16th president of the United States", "United States"),
            ("Winston Churchill", "British prime minister during World War II", "United Kingdom"),
            ("Mahatma Gandhi", "leader of India's independence movement", "India"),
            ("Nelson Mandela", "anti-apartheid leader, first Black president of South Africa", "South Africa"),
            ("Martin Luther King Jr.", "civil rights leader", "United States"),
            ("Mother Teresa", "Catholic nun and missionary", "Albania/India"),
            ("Sigmund Freud", "founder of psychoanalysis", "Austria"),
            ("Karl Marx", "philosopher and economist, author of Das Kapital", "Germany"),
            ("Nikola Tesla", "inventor and electrical engineer, AC power pioneer", "Serbia/Croatia"),
            ("Thomas Edison", "inventor of the practical light bulb and phonograph", "United States"),
            ("Alexander Graham Bell", "inventor of the telephone", "Scotland/Canada"),
            ("Ada Lovelace", "first computer programmer", "England"),
            ("Alan Turing", "father of computer science, cracked the Enigma code", "England"),
            ("Steve Jobs", "co-founder of Apple", "United States"),
            ("Bill Gates", "co-founder of Microsoft", "United States"),
            ("Elon Musk", "founder of SpaceX, CEO of Tesla", "South Africa"),
            ("Mark Zuckerberg", "co-founder of Facebook", "United States"),
            ("Tim Berners-Lee", "inventor of the World Wide Web", "England"),
            ("Neil Armstrong", "first person to walk on the Moon", "United States"),
            ("Yuri Gagarin", "first human in space", "Russia"),
            ("Cleopatra", "last active pharaoh of ancient Egypt", "Egypt"),
            ("Julius Caesar", "Roman general and dictator", "Rome"),
            ("Alexander the Great", "ancient Greek king and conqueror", "Macedonia"),
            ("Genghis Khan", "founder of the Mongol Empire", "Mongolia"),
            ("Christopher Columbus", "explorer credited with reaching the Americas in 1492", "Italy/Spain"),
            ("Marco Polo", "Venetian explorer of Asia", "Italy"),
            ("Florence Nightingale", "founder of modern nursing", "England"),
            ("Marie Antoinette", "queen of France during the French Revolution", "Austria/France"),
            ("Queen Elizabeth II", "longest-reigning British monarch", "United Kingdom"),
            ("Michael Jackson", "singer, the 'King of Pop'", "United States"),
            ("Elvis Presley", "singer, the 'King of Rock and Roll'", "United States"),
            ("Pablo Picasso", "artist, co-founder of Cubism", "Spain"),
            ("Vincent van Gogh", "post-impressionist painter", "Netherlands"),
            ("Frida Kahlo", "Mexican painter", "Mexico"),
            ("Amelia Earhart", "aviator, first woman to fly solo across the Atlantic", "United States"),
            ("Rosa Parks", "civil rights activist", "United States"),
            ("Malala Yousafzai", "education activist, youngest Nobel laureate", "Pakistan"),
            ("Stephen Hawking", "theoretical physicist", "England"),
            ("Rosalind Franklin", "scientist crucial to discovering DNA structure", "England"),
            ("Galileo Galilei", "astronomer who improved the telescope", "Italy"),
            ("Johannes Gutenberg", "inventor of the printing press", "Germany"),
            ("Henry Ford", "founder of Ford Motor Company", "United States"),
            ("The Wright Brothers", "first powered flight in 1903", "United States"),
            ("Ernest Hemingway", "author, winner of the Nobel Prize in Literature", "United States"),
            ("Jane Austen", "author of Pride and Prejudice", "England"),
            ("Charles Dickens", "author of A Tale of Two Cities and Oliver Twist", "England"),
            ("Mark Twain", "author of The Adventures of Tom Sawyer", "United States"),
            ("J.K. Rowling", "author of the Harry Potter series", "England"),
            ("Stephen King", "horror novelist", "United States"),
            ("Oprah Winfrey", "media executive and talk show host", "United States"),
            ("David Attenborough", "natural historian and broadcaster", "England"),
            ("Jane Goodall", "primatologist who studied chimpanzees", "England"),
            ("Edison", "inventor of the light bulb", "United States"),
            ("Aristotle", "ancient Greek philosopher", "Greece"),
            ("Socrates", "ancient Greek philosopher, teacher of Plato", "Greece"),
            ("Plato", "ancient Greek philosopher, student of Socrates", "Greece"),
            ("Confucius", "Chinese philosopher", "China"),
            ("Buddha", "founder of Buddhism", "Nepal/India"),
            ("Jesus Christ", "central figure of Christianity", "Judea"),
            ("Muhammad", "founder of Islam", "Arabia"),
            ("Isaac Asimov", "science fiction author", "Russia/United States"),
            ("Marie Antoinette", "last queen of France before the French Revolution", "France"),
            ("Alexander Fleming", "discovered penicillin in 1928", "Scotland"),
            ("Louis Pasteur", "developed pasteurization and vaccines", "France"),
            ("Jonas Salk", "developed the polio vaccine", "United States"),
            ("Charles Babbage", "designed the first mechanical computer", "England"),
            ("Grace Hopper", "computer scientist, developed COBOL", "United States"),
            ("Hedy Lamarr", "actress and inventor of frequency hopping", "Austria"),
        ]
        for name, fact, origin in people:
            self._add("people", f"who was {name.lower()}", fact, "entity")
            self._add("people", f"{name} nationality", origin, "entity")
            self._add("people", f"{name} known for", fact, "entity")
            self._add("people", f"who is {name.lower()}", fact, "entity")

    # ══════════════════════════════════════════════════════════
    # HISTORY
    # ══════════════════════════════════════════════════════════
    def _load_history(self) -> None:
        events = [
            ("first moon landing", "1969", "Apollo 11 mission by NASA"),
            ("end of World War II", "1945", "in Europe in May, in Japan in September"),
            ("start of World War II", "1939", "with the German invasion of Poland"),
            ("start of World War I", "1914", "after the assassination of Archduke Franz Ferdinand"),
            ("end of World War I", "1918", "with the armistice on November 11"),
            ("American Revolution", "1775-1783", "the United States gained independence"),
            ("US Declaration of Independence", "1776", "signed July 4"),
            ("French Revolution", "1789", "began with the storming of the Bastille"),
            ("fall of the Roman Empire", "476 AD", "the Western Roman Empire fell"),
            ("fall of the Berlin Wall", "1989", "on November 9"),
            ("Magna Carta", "1215", "signed by King John of England"),
            ("printing press invented", "around 1440", "by Johannes Gutenberg"),
            ("Industrial Revolution", "18th-19th century", "began in Britain"),
            ("Renaissance", "14th-17th century", "cultural rebirth in Europe"),
            ("Black Death", "1347-1351", "bubonic plague killed millions in Europe"),
            ("Columbus reached the Americas", "1492", "on October 12"),
            ("sinking of the Titanic", "1912", "on April 15"),
            ("Great Depression", "1929", "began with the stock market crash"),
            ("Cold War", "1947-1991", "between the US and Soviet Union"),
            ("Soviet Union dissolved", "1991", "on December 26"),
            ("Moon landing", "1969", "July 20, Apollo 11"),
            ("Titanic sank", "1912", "on its maiden voyage"),
            ("Pyramids of Giza built", "around 2560 BC", "during the Old Kingdom of Egypt"),
            ("Battle of Waterloo", "1815", "Napoleon defeated"),
            ("US Civil War", "1861-1865", "fought over slavery and union"),
            ("abolition of slavery in the US", "1865", "with the 13th Amendment"),
            ("women's suffrage in the US", "1920", "with the 19th Amendment"),
            ("Manhattan Project", "1942-1945", "developed the atomic bomb"),
            ("atomic bomb on Hiroshima", "1945", "on August 6"),
            ("Cuban Missile Crisis", "1962", "13-day confrontation between US and USSR"),
            ("assassination of JFK", "1963", "in Dallas, Texas"),
            ("first iPhone released", "2007", "by Apple"),
            ("World Wide Web invented", "1989", "by Tim Berners-Lee"),
            ("first email sent", "1971", "by Ray Tomlinson"),
            ("DNA structure discovered", "1953", "by Watson and Crick"),
            ("first computer ENIAC", "1945", "weighed 30 tons"),
            ("first passenger jet service", "1952", "the de Havilland Comet"),
            ("opening of the Eiffel Tower", "1889", "for the World's Fair"),
            ("Panama Canal opened", "1914", "connecting Atlantic and Pacific"),
            ("Suez Canal opened", "1869", "connecting Mediterranean and Red Sea"),
            ("separation of the Beatles", "1970", "the band broke up"),
            ("first Super Bowl", "1967", "Green Bay Packers won"),
            ("first FIFA World Cup", "1930", "held in Uruguay"),
            ("first modern Olympics", "1896", "held in Athens, Greece"),
            ("first man on the Moon", "1969", "Neil Armstrong"),
            ("first woman in space", "1963", "Valentina Tereshkova"),
            ("first space station", "1971", "Salyut 1"),
            ("International Space Station launched", "1998", "first module Zarya"),
            ("Hubble telescope launched", "1990", "into low Earth orbit"),
            ("Stephen Hawking's A Brief History of Time", "1988", "published"),
            ("Gutenberg Bible printed", "1455", "first major book printed in Europe"),
            ("Marco Polo's travels", "1271-1295", "to Asia"),
            ("Aztec Empire fell", "1521", "to Spanish conquistadors"),
            ("Inca Empire fell", "1533", "to Spanish conquistadors"),
            ("Kingdom of Great Britain formed", "1707", "union of England and Scotland"),
            ("US Constitution ratified", "1788", "replaced the Articles of Confederation"),
            ("Louisiana Purchase", "1803", "US bought territory from France"),
            ("California Gold Rush", "1848-1855", "sparked westward expansion"),
            ("Transcontinental Railroad completed", "1869", "in the US"),
            ("Statue of Liberty dedicated", "1886", "gift from France"),
            ("Wright brothers first flight", "1903", "at Kitty Hawk, North Carolina"),
            ("Mount Everest first climbed", "1953", "by Edmund Hillary and Tenzing Norgay"),
            ("Chernobyl disaster", "1986", "nuclear accident in Ukraine"),
            ("Challenger disaster", "1986", "space shuttle exploded"),
            ("South Africa ended apartheid", "1994", "with Nelson Mandela's election"),
            ("Hong Kong returned to China", "1997", "end of British rule"),
            ("September 11 attacks", "2001", "in the United States"),
            ("European Union established", "1993", "with the Maastricht Treaty"),
            ("Euro introduced", "1999", "as virtual currency, 2002 as cash"),
            ("COVID-19 pandemic declared", "2020", "by the WHO on March 11"),
        ]
        for event, answer, note in events:
            self._add("history", f"when was the {event}", answer, "event")
            self._add("history", f"when did the {event} happen", answer, "event")
            self._add("history", f"{event} date", answer, "event")

    # ══════════════════════════════════════════════════════════
    # SCIENCE CONSTANTS + FACTS
    # ══════════════════════════════════════════════════════════
    def _load_science_constants(self) -> None:
        facts = [
            ("speed of light", "299,792,458 meters per second (about 300,000 km/s)"),
            ("speed of sound in air", "about 343 meters per second"),
            ("acceleration due to gravity", "9.81 m/s²"),
            ("boiling point of water", "100°C (212°F)"),
            ("freezing point of water", "0°C (32°F)"),
            ("human body temperature", "37°C (98.6°F)"),
            ("atomic number of hydrogen", "1"),
            ("atomic number of carbon", "6"),
            ("atomic number of oxygen", "8"),
            ("atomic number of gold", "79"),
            ("atomic number of iron", "26"),
            ("chemical formula of water", "H2O"),
            ("chemical formula of salt", "NaCl"),
            ("chemical formula of carbon dioxide", "CO2"),
            ("chemical formula of oxygen gas", "O2"),
            ("chemical formula of methane", "CH4"),
            ("chemical formula of ammonia", "NH3"),
            ("chemical formula of sulfuric acid", "H2SO4"),
            ("chemical formula of glucose", "C6H12O6"),
            ("chemical formula of table sugar", "C12H22O11"),
            ("pH of pure water", "7 (neutral)"),
            ("pH of stomach acid", "around 1-2"),
            ("boiling point of water at sea level", "100°C"),
            ("freezing point of water at sea level", "0°C"),
            ("melting point of iron", "1,538°C"),
            ("melting point of gold", "1,064°C"),
            ("density of water", "1 g/cm³"),
            ("density of air at sea level", "about 1.2 kg/m³"),
            ("diameter of the Earth", "about 12,742 km"),
            ("circumference of the Earth", "about 40,075 km"),
            ("distance from Earth to Moon", "about 384,400 km"),
            ("distance from Earth to Sun", "about 149.6 million km"),
            ("mass of the Earth", "about 5.97 x 10^24 kg"),
            ("age of the Earth", "about 4.54 billion years"),
            ("age of the universe", "about 13.8 billion years"),
            ("age of the Sun", "about 4.6 billion years"),
            ("number of bones in adult human body", "206"),
            ("number of bones in a baby's body", "about 270"),
            ("number of muscles in human body", "over 600"),
            ("number of teeth in adult humans", "32"),
            ("number of chromosomes in humans", "46 (23 pairs)"),
            ("number of genes in humans", "about 20,000-25,000"),
            ("percentage of water in human body", "about 60%"),
            ("human heart beats per minute", "about 60-100 at rest"),
            ("human brain neurons", "about 86 billion"),
            ("largest organ in human body", "the skin"),
            ("longest bone in human body", "the femur (thigh bone)"),
            ("smallest bone in human body", "the stapes (in the ear)"),
            ("hardest natural substance", "diamond"),
            ("most abundant gas in Earth's atmosphere", "nitrogen (about 78%)"),
            ("second most abundant gas in atmosphere", "oxygen (about 21%)"),
            ("most abundant element in the universe", "hydrogen"),
            ("most abundant element in Earth's crust", "oxygen"),
            ("most abundant metal in Earth's crust", "aluminum"),
            ("lightest element", "hydrogen"),
            ("heaviest naturally occurring element", "uranium"),
            ("noble gases", "helium, neon, argon, krypton, xenon, radon"),
            ("alkali metals", "lithium, sodium, potassium, rubidium, cesium, francium"),
            ("halogens", "fluorine, chlorine, bromine, iodine, astatine"),
            ("transition metals", "iron, copper, gold, silver, platinum, etc."),
            ("what is the greenhouse effect", "the trapping of heat by atmospheric gases like CO2"),
            ("what causes the seasons", "Earth's axial tilt of about 23.5 degrees"),
            ("what causes tides", "the gravitational pull of the Moon (and Sun)"),
            ("what causes rainbows", "refraction and reflection of sunlight in water droplets"),
            ("what causes lightning", "electric discharge between charge regions in clouds"),
            ("why is the sky blue", "blue light scatters more than other colors (Rayleigh scattering)"),
            ("what is photosynthesis", "plants converting sunlight, water and CO2 into glucose and oxygen"),
            ("what is DNA", "deoxyribonucleic acid, the molecule carrying genetic information"),
            ("what is a light year", "the distance light travels in one year, about 9.46 trillion km"),
            ("what is gravity", "the force of attraction between masses"),
            ("what is sound", "vibrations that travel through a medium as waves"),
            ("what is a mammal", "warm-blooded vertebrate that nurses its young with milk"),
            ("what is a reptile", "cold-blooded vertebrate with scales"),
            ("what is an amphibian", "cold-blooded vertebrate that lives in water and on land"),
            ("what is a galaxy", "a system of stars, gas and dust held together by gravity"),
            ("what is a black hole", "a region where gravity is so strong nothing can escape"),
            ("what is evolution", "change in species over generations via natural selection"),
            ("what is a virus", "a tiny infectious agent that replicates inside living cells"),
            ("what is a bacteria", "single-celled microorganisms"),
            ("what is a gene", "a segment of DNA that codes for a protein"),
            ("what is a cell", "the basic structural unit of living organisms"),
            ("what is an atom", "the basic unit of matter, made of protons, neutrons and electrons"),
            ("what is a molecule", "two or more atoms chemically bonded"),
            ("what is energy", "the capacity to do work"),
            ("what is entropy", "a measure of disorder in a system"),
            ("what is a photon", "a particle of light"),
            ("what is a neutron star", "the collapsed core of a massive star, extremely dense"),
            ("what is a supernova", "the explosive death of a massive star"),
            ("what is a comet", "an icy body that orbits the Sun, developing a tail near it"),
            ("what is an asteroid", "a rocky body orbiting the Sun, smaller than a planet"),
            ("what is a meteor", "a space rock burning up in Earth's atmosphere"),
        ]
        for topic, answer in facts:
            self._add("science", topic, answer, "fact")

    # ══════════════════════════════════════════════════════════
    # MATH
    # ══════════════════════════════════════════════════════════
    def _load_math(self) -> None:
        facts = [
            ("value of pi", "approximately 3.14159"),
            ("value of e", "approximately 2.71828"),
            ("value of the golden ratio", "approximately 1.618"),
            ("square root of 2", "approximately 1.41421"),
            ("square root of 3", "approximately 1.732"),
            ("square root of 4", "2"),
            ("square root of 9", "3"),
            ("square root of 16", "4"),
            ("square root of 25", "5"),
            ("square root of 36", "6"),
            ("square root of 49", "7"),
            ("square root of 64", "8"),
            ("square root of 81", "9"),
            ("square root of 100", "10"),
            ("2 to the power of 10", "1024"),
            ("2 to the power of 8", "256"),
            ("3 squared", "9"),
            ("4 squared", "16"),
            ("5 squared", "25"),
            ("6 squared", "36"),
            ("7 squared", "49"),
            ("8 squared", "64"),
            ("9 squared", "81"),
            ("10 squared", "100"),
            ("11 squared", "121"),
            ("12 squared", "144"),
            ("13 squared", "169"),
            ("14 squared", "196"),
            ("15 squared", "225"),
            ("sum of angles in a triangle", "180 degrees"),
            ("sum of angles in a quadrilateral", "360 degrees"),
            ("sum of angles in a pentagon", "540 degrees"),
            ("sum of angles in a hexagon", "720 degrees"),
            ("area of a circle formula", "A = πr²"),
            ("circumference of a circle formula", "C = 2πr"),
            ("area of a rectangle formula", "A = length × width"),
            ("area of a triangle formula", "A = (base × height) / 2"),
            ("area of a square formula", "A = side²"),
            ("volume of a cube formula", "V = side³"),
            ("volume of a sphere formula", "V = (4/3)πr³"),
            ("volume of a cylinder formula", "V = πr²h"),
            ("volume of a cone formula", "V = (1/3)πr²h"),
            ("Pythagorean theorem", "a² + b² = c²"),
            ("first prime number", "2"),
            ("smallest prime number", "2"),
            ("smallest even number", "2"),
            ("smallest odd number", "1"),
            ("first 5 prime numbers", "2, 3, 5, 7, 11"),
            ("first 10 prime numbers", "2, 3, 5, 7, 11, 13, 17, 19, 23, 29"),
            ("number 0 is even or odd", "even"),
            ("first 5 fibonacci numbers", "0, 1, 1, 2, 3"),
            ("first 10 fibonacci numbers", "0, 1, 1, 2, 3, 5, 8, 13, 21, 34"),
            ("what is a prime number", "a number greater than 1 divisible only by 1 and itself"),
            ("what is a composite number", "a positive integer with factors other than 1 and itself"),
            ("how many degrees in a right angle", "90"),
            ("how many degrees in a straight angle", "180"),
            ("how many degrees in a full circle", "360"),
            ("what is infinity", "a concept of endlessness, not a real number"),
            ("binary of 2", "10"),
            ("binary of 3", "11"),
            ("binary of 4", "100"),
            ("binary of 5", "101"),
            ("binary of 8", "1000"),
            ("binary of 10", "1010"),
            ("binary of 16", "10000"),
            ("hexadecimal of 10", "A"),
            ("hexadecimal of 15", "F"),
            ("hexadecimal of 16", "10"),
            ("hexadecimal of 255", "FF"),
        ]
        for topic, answer in facts:
            self._add("mathematics", topic, answer, "fact")

    # ══════════════════════════════════════════════════════════
    # COMPUTING
    # ══════════════════════════════════════════════════════════
    def _load_computing(self) -> None:
        facts = [
            ("what does CPU stand for", "Central Processing Unit"),
            ("what does GPU stand for", "Graphics Processing Unit"),
            ("what does RAM stand for", "Random Access Memory"),
            ("what does ROM stand for", "Read-Only Memory"),
            ("what does SSD stand for", "Solid State Drive"),
            ("what does HTTP stand for", "HyperText Transfer Protocol"),
            ("what does HTTPS stand for", "HyperText Transfer Protocol Secure"),
            ("what does HTML stand for", "HyperText Markup Language"),
            ("what does CSS stand for", "Cascading Style Sheets"),
            ("what does SQL stand for", "Structured Query Language"),
            ("what does API stand for", "Application Programming Interface"),
            ("what does JSON stand for", "JavaScript Object Notation"),
            ("what does AI stand for", "Artificial Intelligence"),
            ("what does URL stand for", "Uniform Resource Locator"),
            ("what does DNS stand for", "Domain Name System"),
            ("what does IP stand for", "Internet Protocol"),
            ("what does LAN stand for", "Local Area Network"),
            ("what does WAN stand for", "Wide Area Network"),
            ("what does OS stand for", "Operating System"),
            ("what does USB stand for", "Universal Serial Bus"),
            ("what does PDF stand for", "Portable Document Format"),
            ("what does JPEG stand for", "Joint Photographic Experts Group"),
            ("what does PNG stand for", "Portable Network Graphics"),
            ("how many bits in a byte", "8"),
            ("how many bytes in a kilobyte", "1024"),
            ("how many bytes in a megabyte", "1,048,576 (1024 KB)"),
            ("who created Python", "Guido van Rossum"),
            ("who created Linux", "Linus Torvalds"),
            ("who created C programming language", "Dennis Ritchie"),
            ("who created C++", "Bjarne Stroustrup"),
            ("who created Java", "James Gosling"),
            ("who created JavaScript", "Brendan Eich"),
            ("who created Ruby", "Yukihiro Matsumoto"),
            ("who created Go programming language", "Robert Griesemer, Rob Pike, Ken Thompson (Google)"),
            ("who created Rust", "Graydon Hoare (Mozilla)"),
            ("who created PHP", "Rasmus Lerdorf"),
            ("what year was Python created", "1991"),
            ("what year was Linux created", "1991"),
            ("what year was the first iPhone released", "2007"),
            ("what year was Google founded", "1998"),
            ("what year was Facebook founded", "2004"),
            ("what year was Amazon founded", "1994"),
            ("what year was Microsoft founded", "1975"),
            ("what year was Apple founded", "1976"),
            ("what year was Tesla founded", "2003"),
            ("who founded Google", "Larry Page and Sergey Brin"),
            ("who founded Microsoft", "Bill Gates and Paul Allen"),
            ("who founded Apple", "Steve Jobs, Steve Wozniak and Ronald Wayne"),
            ("who founded Amazon", "Jeff Bezos"),
            ("who founded Facebook", "Mark Zuckerberg"),
            ("largest tech company by market cap", "Apple or Microsoft (varies by year)"),
            ("what is machine learning", "systems that learn from data to improve at tasks"),
            ("what is deep learning", "machine learning using multi-layer neural networks"),
            ("what is a neural network", "a computing system inspired by biological brains"),
            ("what is a transformer model", "a neural architecture based on attention mechanisms"),
            ("what is the Turing test", "a test of whether a machine can imitate human conversation"),
            ("what is open source", "software with source code that anyone can inspect and modify"),
            ("what is cloud computing", "computing services delivered over the internet"),
            ("what is a database", "an organized collection of stored data"),
            ("what is an algorithm", "a step-by-step procedure for solving a problem"),
            ("what is encryption", "converting data into a coded form to prevent unauthorized access"),
            ("what is a firewall", "a security system that monitors and controls network traffic"),
            ("what is a virus in computing", "malicious software that replicates itself"),
            ("what is phishing", "fraudulent attempts to obtain sensitive information"),
            ("what is the internet", "a global network of interconnected computers"),
            ("what is the World Wide Web", "a system of interlinked documents accessed via the internet"),
        ]
        for topic, answer in facts:
            self._add("computing", topic, answer, "fact")

    # ══════════════════════════════════════════════════════════
    # BIOLOGY + HEALTH
    # ══════════════════════════════════════════════════════════
    def _load_biology_health(self) -> None:
        facts = [
            ("largest organ in the human body", "the skin"),
            ("largest internal organ", "the liver"),
            ("largest bone in the human body", "the femur"),
            ("smallest bone in the human body", "the stapes"),
            ("largest muscle in the human body", "the gluteus maximus"),
            ("how many chambers does the human heart have", "4"),
            ("how many lungs does a human have", "2"),
            ("how many kidneys does a human have", "2"),
            ("how many eyes does a spider have", "usually 8"),
            ("how many hearts does an octopus have", "3"),
            ("how many legs does an insect have", "6"),
            ("how many legs does a spider have", "8"),
            ("how many legs does a crab have", "10"),
            ("how many legs does a lobster have", "10"),
            ("fastest land animal", "the cheetah"),
            ("fastest animal overall", "the peregrine falcon"),
            ("largest animal on earth", "the blue whale"),
            ("largest land animal", "the African elephant"),
            ("largest bird", "the ostrich"),
            ("smallest bird", "the bee hummingbird"),
            ("tallest animal", "the giraffe"),
            ("fastest fish", "the sailfish"),
            ("largest fish", "the whale shark"),
            ("largest shark", "the whale shark"),
            ("largest reptile", "the saltwater crocodile"),
            ("longest snake", "the reticulated python"),
            ("most venomous snake", "the inland taipan"),
            ("longest living animal", "the ocean quahog clam (500+ years)"),
            ("how long do elephants live", "60-70 years in the wild"),
            ("how long do dogs live", "10-13 years on average"),
            ("how long do cats live", "12-18 years on average"),
            ("what do bees produce", "honey and beeswax"),
            ("what is a group of lions called", "a pride"),
            ("what is a group of wolves called", "a pack"),
            ("what is a group of crows called", "a murder"),
            ("what is a group of fish called", "a school"),
            ("what is a group of whales called", "a pod"),
            ("what is a baby kangaroo called", "a joey"),
            ("what is a baby horse called", "a foal"),
            ("what is a baby cat called", "a kitten"),
            ("what is a baby dog called", "a puppy"),
            ("what is a baby cow called", "a calf"),
            ("what is a baby sheep called", "a lamb"),
            ("what is a baby goat called", "a kid"),
            ("what is a baby duck called", "a duckling"),
            ("what is a baby chicken called", "a chick"),
            ("what is a baby frog called", "a tadpole"),
            ("what is a baby owl called", "an owlet"),
            ("how many stomachs does a cow have", "4"),
            ("do bats have wings", "yes, they are the only flying mammals"),
            ("are penguins birds", "yes, but they cannot fly"),
            ("can penguins fly", "no"),
            ("do ostriches fly", "no, they are flightless birds"),
            ("what color is a flamingo", "pink (from its diet of shrimp and algae)"),
            ("what is the national animal of Australia", "the kangaroo (and emu)"),
            ("what animal is known as man's best friend", "the dog"),
            ("what is the tallest grass", "bamboo"),
            ("how fast does bamboo grow", "up to 91 cm per day"),
            ("what is the largest flower", "Rafflesia arnoldii"),
            ("what is the oldest living tree species", "bristlecone pine"),
            ("how do plants make food", "photosynthesis using sunlight, water and CO2"),
            ("what is pollination", "transfer of pollen to fertilize plants"),
            ("what is a predator", "an animal that hunts other animals"),
            ("what is prey", "an animal hunted by predators"),
            ("what is a herbivore", "an animal that eats only plants"),
            ("what is a carnivore", "an animal that eats only meat"),
            ("what is an omnivore", "an animal that eats both plants and meat"),
            ("what is a nocturnal animal", "an animal active at night"),
            ("what is hibernation", "a state of deep sleep to survive winter"),
            ("what is camouflage", "blending in with the environment to hide"),
            ("what is a food chain", "the sequence of who eats whom in an ecosystem"),
            ("what is an ecosystem", "a community of organisms and their environment"),
            ("what is biodiversity", "the variety of life in an ecosystem"),
            ("what is the largest rainforest", "the Amazon Rainforest"),
            ("what is the driest place on earth", "the Atacama Desert"),
            ("what is the wettest place on earth", "Mawsynram, India"),
            ("what is the hottest place on earth", "Death Valley, California"),
            ("what is the coldest place on earth", "Antarctica"),
            ("what is the highest point on earth", "Mount Everest"),
            ("what is the lowest point on earth", "the Dead Sea shoreline / Mariana Trench"),
            ("what is the windiest place on earth", "Commonwealth Bay, Antarctica"),
        ]
        for topic, answer in facts:
            self._add("biology", topic, answer, "fact")

    # ══════════════════════════════════════════════════════════
    # MISCELLANEOUS GENERAL KNOWLEDGE
    # ══════════════════════════════════════════════════════════
    def _load_misc(self) -> None:
        facts = [
            ("capital of the world is", "no official capital, but New York is the UN headquarters"),
            ("how many keys on a standard piano", "88"),
            ("how many strings on a standard guitar", "6"),
            ("how many strings on a violin", "4"),
            ("how many strings on a cello", "4"),
            ("how many strings on a harp", "47"),
            ("how many colors in a rainbow", "7 (red, orange, yellow, green, blue, indigo, violet)"),
            ("primary colors", "red, blue, yellow (subtractive: cyan, magenta, yellow)"),
            ("how many sides does a triangle have", "3"),
            ("how many sides does a square have", "4"),
            ("how many sides does a pentagon have", "5"),
            ("how many sides does a hexagon have", "6"),
            ("how many sides does an octagon have", "8"),
            ("how many sides does a decagon have", "10"),
            ("how many seconds in a minute", "60"),
            ("how many minutes in an hour", "60"),
            ("how many hours in a day", "24"),
            ("how many days in a week", "7"),
            ("how many days in a year", "365 (366 in a leap year)"),
            ("how many days in February", "28 (29 in a leap year)"),
            ("how many months have 31 days", "7"),
            ("how many weeks in a year", "52"),
            ("how many days in a leap year", "366"),
            ("how many years in a decade", "10"),
            ("how many years in a century", "100"),
            ("how many years in a millennium", "1000"),
            ("how many quarters in a year", "4"),
            ("first day of the week", "Sunday (or Monday in many countries)"),
            ("last month of the year", "December"),
            ("first month of the year", "January"),
            ("month with the shortest name", "May (3 letters)"),
            ("what comes after September", "October"),
            ("what comes before March", "February"),
            ("what is the longest word in English", "pneumonoultramicroscopicsilicovolcanoconiosis"),
            ("what is the most common letter in English", "e"),
            ("what is the shortest sentence in English", "I am."),
            ("how many letters in the alphabet", "26"),
            ("how many vowels in the English alphabet", "5 (a, e, i, o, u, sometimes y)"),
            ("first letter of the alphabet", "A"),
            ("last letter of the alphabet", "Z"),
            ("how many players on a soccer team", "11"),
            ("how many players on a basketball team", "5"),
            ("how many players on a cricket team", "11"),
            ("how many players on a baseball team", "9"),
            ("how many players on a rugby team", "15"),
            ("how many players on an ice hockey team", "6 (on the ice)"),
            ("how long is a marathon", "42.195 km (26.2 miles)"),
            ("how long is an Olympic swimming pool", "50 meters"),
            ("how many Olympic rings", "5"),
            ("what do the Olympic rings represent", "the five inhabited continents"),
            ("how often is the FIFA World Cup held", "every 4 years"),
            ("how often is the Olympics held", "every 4 years"),
            ("what country invented soccer", "England (modern rules)"),
            ("what country invented basketball", "United States (1891)"),
            ("what country invented cricket", "England"),
            ("what country invented baseball", "United States"),
            ("largest stadium in the world", "Rungrado May Day Stadium, North Korea"),
            ("how many carats is pure gold", "24 carats"),
            ("how many carats is 18k gold", "18 parts gold out of 24 (75% gold)"),
            ("what is sterling silver", "92.5% silver alloy"),
            ("how many playing cards in a standard deck", "52 (plus 2 jokers)"),
            ("how many suits in a card deck", "4 (hearts, diamonds, clubs, spades)"),
            ("what is checkmate in chess", "when the king is threatened and cannot escape"),
            ("how many squares on a chessboard", "64"),
            ("what are the colors on a chessboard called", "white and black (light and dark)"),
            ("what is the most popular sport in the world", "soccer (football)"),
            ("what is the oldest sport", "wrestling (or running)"),
            ("what is the national sport of Japan", "sumo wrestling"),
            ("what is the national sport of Canada", "lacrosse (and ice hockey)"),
            ("what is the most watched sporting event", "the FIFA World Cup final"),
            ("highest grossing film of all time", "Avatar (or Avengers: Endgame, varies by inflation)"),
            ("what is the longest-running TV show", "The Simpsons (or Guiding Light)"),
            ("what year did the first movie with sound appear", "1927 (The Jazz Singer)"),
            ("who directed Titanic", "James Cameron"),
            ("who directed Star Wars", "George Lucas"),
            ("who played Iron Man", "Robert Downey Jr."),
            ("who played Harry Potter", "Daniel Radcliffe"),
            ("who played James Bond first", "Sean Connery"),
            ("how many Star Wars main saga films", "9 (1977-2019)"),
            ("what is the highest-grossing movie franchise", "Marvel Cinematic Universe"),
            ("what is the best-selling book of all time", "the Bible"),
            ("what is the best-selling fiction book", "Don Quixote"),
            ("most translated book", "the Bible"),
            ("who wrote the Iliad", "Homer"),
            ("who wrote the Odyssey", "Homer"),
            ("who wrote Romeo and Juliet", "William Shakespeare"),
            ("who wrote Hamlet", "William Shakespeare"),
            ("who wrote Macbeth", "William Shakespeare"),
            ("who wrote Pride and Prejudice", "Jane Austen"),
            ("who wrote Moby Dick", "Herman Melville"),
            ("who wrote War and Peace", "Leo Tolstoy"),
            ("who wrote Crime and Punishment", "Fyodor Dostoevsky"),
            ("who wrote The Great Gatsby", "F. Scott Fitzgerald"),
            ("who wrote To Kill a Mockingbird", "Harper Lee"),
            ("who wrote 1984", "George Orwell"),
            ("who wrote Animal Farm", "George Orwell"),
            ("who wrote The Lord of the Rings", "J.R.R. Tolkien"),
            ("who wrote Harry Potter", "J.K. Rowling"),
            ("who wrote The Hobbit", "J.R.R. Tolkien"),
            ("who wrote Frankenstein", "Mary Shelley"),
            ("who wrote Dracula", "Bram Stoker"),
            ("who wrote The Divine Comedy", "Dante Alighieri"),
            ("who wrote Don Quixote", "Miguel de Cervantes"),
            ("who painted the Mona Lisa", "Leonardo da Vinci"),
            ("who painted the Last Supper", "Leonardo da Vinci"),
            ("who painted the Starry Night", "Vincent van Gogh"),
            ("who painted Guernica", "Pablo Picasso"),
            ("who painted the Scream", "Edvard Munch"),
            ("who sculpted David", "Michelangelo"),
            ("who sculpted the Pieta", "Michelangelo"),
            ("who sculpted the Thinker", "Auguste Rodin"),
            ("who composed the Four Seasons", "Antonio Vivaldi"),
            ("who composed the Moonlight Sonata", "Ludwig van Beethoven"),
            ("who composed Eine kleine Nachtmusik", "Wolfgang Amadeus Mozart"),
            ("who composed the 1812 Overture", "Pyotr Ilyich Tchaikovsky"),
            ("who composed Swan Lake", "Pyotr Ilyich Tchaikovsky"),
            ("who composed the Blue Danube", "Johann Strauss II"),
            ("who composed the Nutcracker", "Pyotr Ilyich Tchaikovsky"),
            ("who composed Carmen", "Georges Bizet"),
            ("what is the capital of the music world", "Vienna, Austria"),
            ("how many symphonies did Beethoven write", "9"),
            ("how many symphonies did Mozart write", "41"),
            ("what is the national anthem of the United States", "The Star-Spangled Banner"),
            ("what is the national anthem of France", "La Marseillaise"),
            ("what is the national anthem of the UK", "God Save the King"),
            ("what is the largest religion in the world", "Christianity"),
            ("second largest religion in the world", "Islam"),
            ("third largest religion in the world", "Hinduism"),
            ("what is the holy book of Christianity", "the Bible"),
            ("what is the holy book of Islam", "the Quran"),
            ("what is the holy book of Judaism", "the Torah"),
            ("what is the holy book of Hinduism", "the Vedas"),
            ("what is the holy book of Buddhism", "the Tripitaka"),
            ("what is the oldest religion", "Hinduism"),
            ("how many pillars of Islam", "5"),
            ("how many commandments in the Bible", "10"),
            ("what does Christianity believe", "in one God and Jesus Christ as savior"),
            ("what does Islam believe", "in one God (Allah) and Muhammad as the final prophet"),
            ("what does Buddhism teach", "the Four Noble Truths and the Eightfold Path"),
            ("what is the symbol of peace", "the dove"),
            ("what does the Statue of Liberty represent", "liberty and freedom"),
            ("what is the tallest building in the world", "Burj Khalifa (828 m)"),
            ("what is the tallest building in the US", "One World Trade Center"),
            ("what is the oldest university", "the University of Al-Qarawiyyin (859 AD)"),
            ("what is the most expensive painting ever sold", "Salvator Mundi by Leonardo da Vinci"),
            ("what is the currency of the United States", "US dollar"),
            ("what is the currency of the UK", "pound sterling"),
            ("what is the currency of Japan", "Japanese yen"),
            ("what is the currency of China", "Chinese yuan (renminbi)"),
            ("what is the currency of the Eurozone", "euro"),
            ("what is the currency of India", "Indian rupee"),
            ("what is the currency of Russia", "Russian ruble"),
            ("what is the currency of Brazil", "Brazilian real"),
            ("what is the currency of Mexico", "Mexican peso"),
            ("what is the currency of Australia", "Australian dollar"),
            ("what is the currency of Canada", "Canadian dollar"),
            ("what is the currency of Switzerland", "Swiss franc"),
            ("what is the currency of South Africa", "South African rand"),
            ("what is the currency of Saudi Arabia", "Saudi riyal"),
            ("what is the currency of Nigeria", "Nigerian naira"),
            ("what is the currency of Egypt", "Egyptian pound"),
            ("what is the currency of Turkey", "Turkish lira"),
            ("what is the currency of South Korea", "South Korean won"),
            ("what is the currency of Sweden", "Swedish krona"),
            ("what is the currency of Norway", "Norwegian krone"),
            ("what is the currency of Denmark", "Danish krone"),
            ("what is the currency of Poland", "Polish zloty"),
            ("what is the currency of Indonesia", "Indonesian rupiah"),
            ("what is the currency of Thailand", "Thai baht"),
            ("what is the currency of Vietnam", "Vietnamese dong"),
            ("what is the currency of the Philippines", "Philippine peso"),
            ("what is the currency of Singapore", "Singapore dollar"),
            ("what is the currency of Malaysia", "Malaysian ringgit"),
            ("what is the currency of the United Arab Emirates", "UAE dirham"),
            ("what is the currency of Argentina", "Argentine peso"),
            ("what is the currency of Chile", "Chilean peso"),
            ("what is the currency of Colombia", "Colombian peso"),
            ("what is the currency of Peru", "Peruvian sol"),
            ("what is the currency of Venezuela", "Venezuelan bolivar"),
            ("what is the currency of Pakistan", "Pakistani rupee"),
            ("what is the currency of Bangladesh", "Bangladeshi taka"),
            ("what is the currency of Iran", "Iranian rial"),
            ("what is the currency of Iraq", "Iraqi dinar"),
            ("what is the currency of Israel", "Israeli new shekel"),
            ("what is the currency of New Zealand", "New Zealand dollar"),
            ("what is the currency of Iceland", "Icelandic krona"),
            ("what is the currency of Greece", "euro"),
            ("what is the currency of Portugal", "euro"),
            ("what is the currency of Spain", "euro"),
            ("what is the currency of Italy", "euro"),
            ("what is the currency of Germany", "euro"),
            ("what is the currency of France", "euro"),
            ("what is the currency of Belgium", "euro"),
            ("what is the currency of the Netherlands", "euro"),
            ("what is the currency of Austria", "euro"),
            ("what is the currency of Finland", "euro"),
            ("what is the currency of Ireland", "euro"),
            ("what is the currency of Luxembourg", "euro"),
            ("what is the currency of Slovakia", "euro"),
            ("what is the currency of Slovenia", "euro"),
            ("what is the currency of Latvia", "euro"),
            ("what is the currency of Lithuania", "euro"),
            ("what is the currency of Estonia", "euro"),
            ("what is the currency of Malta", "euro"),
            ("what is the currency of Cyprus", "euro"),
            ("what is the currency of Croatia", "euro"),
            ("what is the currency of Morocco", "Moroccan dirham"),
            ("what is the currency of Kenya", "Kenyan shilling"),
            ("what is the currency of Ghana", "Ghanaian cedi"),
            ("what is the currency of Ethiopia", "Ethiopian birr"),
            ("what is the currency of Tanzania", "Tanzanian shilling"),
            ("what is the currency of Uganda", "Ugandan shilling"),
            ("what is the currency of Cuba", "Cuban peso"),
            ("what is the currency of Jamaica", "Jamaican dollar"),
            ("what is the currency of Qatar", "Qatari riyal"),
            ("what is the currency of Kuwait", "Kuwaiti dinar"),
            ("what is the currency of Ukraine", "Ukrainian hryvnia"),
            ("what is the currency of Romania", "Romanian leu"),
            ("what is the currency of Hungary", "Hungarian forint"),
            ("what is the currency of Czech Republic", "Czech koruna"),
            ("what is the currency of Bulgaria", "Bulgarian lev"),
            ("what is the currency of Serbia", "Serbian dinar"),
            ("what is the currency of Croatia", "euro"),
        ]
        for topic, answer in facts:
            self._add("general", topic, answer, "fact")


    def _load_qa_records(self) -> None:
        """Curated Q&A facts covering common open-domain questions
        (records, superlatives, who-questions, how-many)."""
        facts = [
            # Animals / nature
            ("largest mammal in the world", "the blue whale"),
            ("largest mammal on land", "the African elephant"),
            ("largest animal in the world", "the blue whale"),
            ("fastest land animal", "the cheetah"),
            ("fastest animal in the world", "the peregrine falcon"),
            ("tallest animal in the world", "the giraffe"),
            ("largest bird in the world", "the ostrich"),
            ("smallest bird in the world", "the bee hummingbird"),
            ("largest reptile in the world", "the saltwater crocodile"),
            ("largest snake in the world", "the green anaconda"),
            ("longest snake in the world", "the reticulated python"),
            ("only mammal capable of true flight", "the bat"),
            ("only mammal that can fly", "the bat"),
            ("largest rodent in the world", "the capybara"),
            ("largest fish in the world", "the whale shark"),
            ("largest shark in the world", "the whale shark"),
            ("national animal of Australia", "the kangaroo (and emu)"),
            ("national animal of Canada", "the beaver (and Canadian horse)"),
            ("national animal of the United States", "the bald eagle"),
            ("national animal of India", "the Bengal tiger"),
            ("national animal of China", "the giant panda"),
            ("national animal of Japan", "the Japanese macaque (snow monkey)"),
            ("national flower of Japan", "the cherry blossom (sakura)"),
            ("national flower of the United States", "the rose"),
            ("national flower of England", "the Tudor rose"),
            ("national sport of Japan", "sumo wrestling"),
            ("national sport of Canada", "lacrosse (summer) and ice hockey (winter)"),
            ("national sport of the United States", "baseball"),
            # Human body
            ("longest bone in the human body", "the femur (thigh bone)"),
            ("largest bone in the human body", "the femur (thigh bone)"),
            ("strongest bone in the human body", "the femur"),
            ("largest organ of the human body", "the skin"),
            ("largest internal organ of the human body", "the liver"),
            ("smallest bone in the human body", "the stapes (stirrup bone in the ear)"),
            ("hardest substance in the human body", "tooth enamel"),
            ("most abundant element in the human body", "oxygen"),
            ("number of bones in adult human body", "206"),
            ("number of teeth in adult human mouth", "32"),
            ("number of chambers in the human heart", "4"),
            ("how many hearts does an octopus have", "3"),
            ("how many hearts does a human have", "1"),
            # Science / space
            ("number of planets in solar system", "8"),
            ("number of planets in the solar system", "8"),
            ("largest planet in the solar system", "Jupiter"),
            ("smallest planet in the solar system", "Mercury"),
            ("hottest planet in the solar system", "Venus"),
            ("coldest planet in the solar system", "Uranus"),
            ("planet with the most moons", "Saturn"),
            ("red planet", "Mars"),
            ("closest star to Earth", "the Sun"),
            ("closest star to the Sun", "Proxima Centauri"),
            ("name of our galaxy", "the Milky Way"),
            ("closest galaxy to the Milky Way", "the Andromeda Galaxy"),
            ("center of an atom", "the nucleus"),
            ("smallest unit of life", "the cell"),
            ("powerhouse of the cell", "the mitochondria"),
            ("control center of the cell", "the nucleus"),
            ("study of fossils", "paleontology"),
            ("study of stars", "astronomy"),
            ("study of the Earth", "geology"),
            ("study of weather", "meteorology"),
            ("most abundant gas in earth atmosphere", "nitrogen (about 78%)"),
            ("most abundant gas in the earth atmosphere", "nitrogen (about 78%)"),
            ("most abundant element in the universe", "hydrogen"),
            ("most abundant element in the earth crust", "oxygen"),
            ("force that pulls objects toward earth", "gravity"),
            ("hardest natural substance on earth", "diamond"),
            ("softest mineral on the mohs scale", "talc"),
            ("chemical symbol for gold", "Au"),
            ("chemical symbol for silver", "Ag"),
            ("chemical symbol for iron", "Fe"),
            ("chemical symbol for sodium", "Na"),
            ("chemical symbol for oxygen", "O"),
            ("chemical symbol for hydrogen", "H"),
            ("chemical symbol for carbon", "C"),
            ("chemical symbol for nitrogen", "N"),
            ("chemical symbol for potassium", "K"),
            ("chemical symbol for calcium", "Ca"),
            ("chemical symbol for copper", "Cu"),
            ("chemical symbol for lead", "Pb"),
            ("chemical symbol for mercury", "Hg"),
            ("chemical symbol for tin", "Sn"),
            ("chemical formula for table salt", "NaCl"),
            ("chemical formula for water", "H2O"),
            ("element with atomic number 1", "hydrogen"),
            ("element with atomic number 2", "helium"),
            ("element with atomic number 6", "carbon"),
            ("element with atomic number 8", "oxygen"),
            ("element with atomic number 26", "iron"),
            ("element with atomic number 47", "silver"),
            ("element with atomic number 79", "gold"),
            # Math / numbers
            ("number of days in a leap year", "366"),
            ("number of days in a normal year", "365"),
            ("number of weeks in a year", "52"),
            ("number of hours in a day", "24"),
            ("number of minutes in an hour", "60"),
            ("number of seconds in a minute", "60"),
            ("number of months in a year", "12"),
            ("number of days in a week", "7"),
            ("number of colors in a rainbow", "7"),
            ("number of colors in rainbow", "7"),
            ("number of players on a soccer team", "11"),
            ("number of players on a football team", "11"),
            ("number of players on a basketball team", "5"),
            ("number of players on a cricket team", "11"),
            ("number of strings on a standard guitar", "6"),
            ("number of strings on a violin", "4"),
            ("number of strings on a ukulele", "4"),
            ("number of keys on a standard piano", "88"),
            ("number of continents", "7"),
            ("number of oceans", "5"),
            ("number of time zones in Russia", "11"),
            ("number of time zones in the united states", "6 (plus territories)"),
            ("number of states in the United States", "50"),
            ("number of countries in the world", "195 (193 UN members plus 2 observers)"),
            ("number of official languages of the UN", "6"),
            ("number of permanent members of the UN Security Council", "5"),
            ("number of hearts an octopus has", "3"),
            ("value of pi to two decimal places", "3.14"),
            ("largest prime number under 100", "97"),
            ("square root of 144", "12"),
            ("square root of 100", "10"),
            ("square root of 81", "9"),
            ("square root of 64", "8"),
            ("square root of 49", "7"),
            # History / people (who-questions)
            ("who was the first president of the United States", "George Washington"),
            ("who was the president of the United States during the american civil war", "Abraham Lincoln"),
            ("who was the president of the United States during world war two", "Franklin D. Roosevelt"),
            ("who was the British prime minister during most of World War II", "Winston Churchill"),
            ("who was the prime minister of the United Kingdom during world war two", "Winston Churchill"),
            ("who developed the theory of relativity", "Albert Einstein"),
            ("who came up with the theory of relativity", "Albert Einstein"),
            ("theory of relativity", "developed by Albert Einstein in 1905 (special) and 1915 (general)"),
            ("who discovered gravity", "Isaac Newton"),
            ("who discovered the laws of motion", "Isaac Newton"),
            ("who discovered the structure of DNA", "James Watson and Francis Crick"),
            ("who discovered radium", "Marie Curie"),
            ("who discovered the electron", "J.J. Thomson"),
            ("who discovered the nucleus of the atom", "Ernest Rutherford"),
            ("who proposed the theory of evolution", "Charles Darwin"),
            ("who proposed the heliocentric model", "Nicolaus Copernicus"),
            ("who invented the telescope", "Hans Lippershey (patent); Galileo improved it"),
            ("who invented the microscope", "Zacharias Janssen (c. 1590)"),
            ("who invented the battery", "Alessandro Volta"),
            ("who invented dynamite", "Alfred Nobel"),
            ("who invented the periodic table", "Dmitri Mendeleev"),
            ("who invented the polio vaccine", "Jonas Salk"),
            ("who developed the smallpox vaccine", "Edward Jenner"),
            ("who invented the sewing machine", "Elias Howe (improved by Singer)"),
            ("who invented the cotton gin", "Eli Whitney"),
            ("who invented the bicycle", "Karl von Drais"),
            ("who invented the elevator", "Elisha Otis"),
            ("who invented the camera", "Louis Daguerre (daguerreotype)"),
            ("who invented photography", "Louis Daguerre and Nicéphore Niépce"),
            ("who invented the zipper", "Gideon Sundback"),
            ("who wrote the theory of natural selection", "Charles Darwin"),
            ("who wrote The Origin of Species", "Charles Darwin"),
            ("who painted the Mona Lisa", "Leonardo da Vinci"),
            ("who painted the ceiling of the Sistine Chapel", "Michelangelo"),
            ("who wrote the Declaration of Independence", "Thomas Jefferson"),
            # Year/history facts
            ("year the Berlin Wall fell", "1989"),
            ("when did the Berlin Wall fall", "1989"),
            ("year the American Civil War ended", "1865"),
            ("when did the American Civil War end", "1865"),
            ("year the American Civil War began", "1861"),
            ("year man first landed on the moon", "1969"),
            ("when did the Soviet Union collapse", "1991"),
            ("year the Soviet Union was founded", "1922"),
            ("year the Soviet Union dissolved", "1991"),
            ("year the Titanic sank", "1912"),
            ("year World War II started", "1939"),
            ("year World War II ended", "1945"),
            ("year World War I started", "1914"),
            ("year World War I ended", "1918"),
            ("year the Cold War ended", "1991"),
            ("year the French Revolution began", "1789"),
            ("year the American Revolution began", "1775"),
            ("year the American Revolution ended", "1783"),
            ("year the US Declaration of Independence was signed", "1776"),
            ("year Columbus reached the Americas", "1492"),
            ("ancient Egyptian writing system", "hieroglyphics"),
            ("writing system of ancient Egypt", "hieroglyphics"),
            ("what were Egyptian hieroglyphs", "the ancient Egyptian writing system using pictorial symbols"),
            ("year the printing press was invented", "around 1440"),
            ("year the first moon landing happened", "1969"),
            ("who was the first person to walk on the moon", "Neil Armstrong"),
            # Science misc
            ("chemical symbol for water", "H2O (chemical formula)"),
            ("gas that plants absorb", "carbon dioxide"),
            ("gas plants absorb from the atmosphere", "carbon dioxide"),
            ("what gas do plants take in", "carbon dioxide"),
            ("gas plants release", "oxygen"),
            ("center of an atom", "the nucleus"),
            ("centre of an atom", "the nucleus"),
            ("what is inside the nucleus of an atom", "protons and neutrons"),
            ("study of fossils", "paleontology"),
            ("study of ancient life", "paleontology"),
            ("study of cells", "cell biology (cytology)"),
            ("study of the brain", "neuroscience"),
            ("study of earthquakes", "seismology"),
            ("study of volcanoes", "volcanology"),
            ("study of weather and climate", "meteorology"),
            ("what is the powerhouse of the cell", "the mitochondria"),
            ("what does mitochondria do", "produces energy for the cell"),
            ("boiling point of water in celsius", "100°C"),
            ("freezing point of water in celsius", "0°C"),
            ("element that has atomic number 1", "hydrogen"),
            ("element with atomic number 1", "hydrogen"),
            ("what is the atomic number of hydrogen", "1"),
            ("atomic number of carbon", "6"),
            ("atomic number of oxygen", "8"),
            ("atomic number of gold", "79"),
            ("atomic number of iron", "26"),
            ("what is the atomic number of iron", "26"),
            ("what is the atomic number of gold", "79"),
            ("what is the most abundant gas in the atmosphere", "nitrogen (about 78%)"),
            ("what is the second most abundant gas in the atmosphere", "oxygen (about 21%)"),
            ("speed of light in km per second", "about 300,000 km/s"),
            ("how fast is the speed of light", "about 300,000 km/s (299,792,458 m/s)"),
            ("what is the distance light travels in a year", "about 9.46 trillion km (a light year)"),
            ("who was the 16th president of the United States", "Abraham Lincoln"),
            ("who was the first man on the moon", "Neil Armstrong"),
            ("who was the first woman to win a Nobel Prize", "Marie Curie"),
            ("who was the first person in space", "Yuri Gagarin"),
            ("who was the first woman in space", "Valentina Tereshkova"),
            ("who painted the ceiling of the Sistine Chapel", "Michelangelo"),
            ("who painted the Sistine Chapel", "Michelangelo"),
            ("who wrote the theory of evolution by natural selection", "Charles Darwin"),
            ("who developed the theory of evolution", "Charles Darwin"),
            ("who wrote the Declaration of Independence", "Thomas Jefferson"),
            ("who was the first emperor of Rome", "Augustus (Octavian)"),
            ("who discovered America in 1492", "Christopher Columbus"),
            ("who discovered penicillin", "Alexander Fleming"),
            ("who invented the telephone", "Alexander Graham Bell"),
            ("who invented the light bulb", "Thomas Edison"),
            ("who invented the printing press", "Johannes Gutenberg"),
            ("who invented the airplane", "the Wright brothers"),
            ("who invented the computer", "Charles Babbage (concept)"),
            ("who invented the internet", "no single inventor; developed by ARPANET researchers"),
            ("who invented the World Wide Web", "Tim Berners-Lee"),
            ("who invented the steam engine", "James Watt (improved)"),
            ("who invented the radio", "Guglielmo Marconi"),
            ("who invented the automobile", "Karl Benz"),
            ("who founded Microsoft", "Bill Gates and Paul Allen"),
            ("who founded Apple", "Steve Jobs, Steve Wozniak and Ronald Wayne"),
            ("who founded Amazon", "Jeff Bezos"),
            ("who founded Tesla", "Martin Eberhard and Marc Tarpenning (2003); Elon Musk joined as major investor"),
            ("who founded SpaceX", "Elon Musk"),
            ("who founded Facebook", "Mark Zuckerberg and Harvard roommates"),
            ("who founded Google", "Larry Page and Sergey Brin"),
            ("who founded Alibaba", "Jack Ma"),
            ("who founded Netflix", "Reed Hastings and Marc Randolph"),
            ("who was the father of modern physics", "often credited to Galileo Galilei or Isaac Newton; modern physics to Albert Einstein"),
            ("father of modern physics", "Galileo Galilei or Isaac Newton"),
            ("father of modern science", "Galileo Galilei"),
            ("father of geometry", "Euclid"),
            ("father of medicine", "Hippocrates"),
            ("father of computers", "Charles Babbage"),
            ("father of the atomic bomb", "J. Robert Oppenheimer"),
            ("father of modern chemistry", "Antoine Lavoisier"),
            ("who wrote the Iliad", "Homer"),
            ("who was the first Roman emperor", "Augustus"),
            ("who was the first king of England", "Athelstan"),
            ("who was the longest-reigning British monarch", "Queen Elizabeth II"),
            ("who was the youngest US president", "Theodore Roosevelt (42)"),
            ("who was the oldest US president", "Joe Biden (78 at inauguration)"),
            # Misc world records
            ("largest country in the world", "Russia"),
            ("smallest country in the world", "Vatican City"),
            ("largest island in the world", "Greenland"),
            ("largest lake in the world", "the Caspian Sea"),
            ("deepest lake in the world", "Lake Baikal"),
            ("longest river in the world", "the Nile"),
            ("tallest mountain in the world", "Mount Everest"),
            ("largest desert in the world", "the Antarctic Desert"),
            ("largest hot desert in the world", "the Sahara"),
            ("largest rainforest in the world", "the Amazon"),
            ("largest ocean in the world", "the Pacific"),
            ("deepest ocean in the world", "the Pacific"),
            ("largest city in the world by population", "Tokyo"),
            ("largest city in the world", "Tokyo (by metro population)"),
            ("most populous city in Australia", "Sydney"),
            ("largest city in Australia", "Sydney"),
            ("capital of Australia", "Canberra"),
            ("most populous city in the United States", "New York City"),
            ("most populous city in the UK", "London"),
            ("most populous city in Japan", "Tokyo"),
            ("most populous city in India", "Mumbai (Delhi by metro)"),
            ("most populous country in the world", "India"),
            ("second most populous country in the world", "China"),
            ("largest continent in the world", "Asia"),
            ("smallest continent in the world", "Australia (Oceania)"),
            ("largest waterfall in the world", "Angel Falls"),
            ("longest wall in the world", "the Great Wall of China"),
            ("largest building in the world", "the Boeing Everett Factory (by volume)"),
            ("tallest building in the world", "Burj Khalifa (828 m)"),
            ("sea that separates Europe and Africa", "the Mediterranean Sea"),
            ("country known as the land of the rising sun", "Japan"),
            ("country with the largest population", "India"),
        ]
        for topic, answer in facts:
            self._add("qa", topic, answer, "fact")


# Singleton
_mega: MegaKnowledge | None = None


def get_mega_knowledge() -> MegaKnowledge:
    global _mega
    if _mega is None:
        _mega = MegaKnowledge()
    return _mega