"""Generate additional training queries for the intent classifier.

Target: ~30 diverse, realistic queries per intent class.
Output: JSONL lines matching the existing schema (text, intent, sub_intent).
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path

QUERIES: dict[str, list[str]] = {
    "lead_generation": [
        "find CTOs at Series B startups in San Francisco",
        "scrape LinkedIn for marketing directors in healthcare",
        "get a list of Shopify store owners doing 7 figures",
        "who are the top AI researchers at Google Brain",
        "find angel investors interested in climate tech",
        "look up SaaS companies with 50-200 employees in Austin",
        "build a prospect list of dentists in Chicago",
        "find e-commerce brands spending on Facebook ads",
        "get me contact info for VCs in the crypto space",
        "which agencies handle PR for fintech startups",
        "find hiring managers at FAANG companies",
        "scrape Y Combinator directory for W24 batch",
        "get founder emails from Product Hunt launches",
        "find companies that just raised seed funding in biotech",
        "look for real estate agencies using CRM software",
        "findfreelance designers on Dribbble with React skills",
        "get a list of Shopify Plus partners",
        "who are the decision makers at Tesla supply chain",
        "find marketing agencies in London with 20+ employees",
        "scrape Crunchbase for edtech startups in India",
        "get contacts for HR directors at Fortune 500",
        "find startup CTOs who recently posted about Rust",
        "look for data science teams hiring remote",
        "find companies using Salesforce in manufacturing",
        "get me a prospect list of accounting firms in NYC",
        "which fintechs are hiring ML engineers right now",
        "find LinkedIn profiles of product managers in Seattle",
        "scrape AngelList for remote-first companies",
        "get founder names from TechCrunch funding announcements",
        "find ecommerce brands on Shopify doing influencer marketing",
    ],
    "web_search": [
        "search for the latest news about OpenAI",
        "find articles about quantum computing breakthroughs",
        "look up how to install Docker on Ubuntu",
        "search for reviews of the MacBook Pro M4",
        "find the current price of Bitcoin",
        "search for research papers on transformer architectures",
        "look up the weather in Tokyo next week",
        "find the best restaurants near me",
        "search for Python async tutorial",
        "find compare pricing for cloud hosting providers",
        "look up what happened at CES 2026",
        "search for alternatives to Notion",
        "find documentation for FastAPI authentication",
        "search Reddit for opinions on React vs Vue",
        "look up stock price of NVIDIA",
        "find the latest salary data for software engineers",
        "search for career opportunities in AI safety",
        "find government regulations for AI in healthcare",
        "look up how to start a LLC in Delaware",
        "search for recent acquisitions in the adtech space",
        "find open source alternatives to Figma",
        "look up tennis scores from Wimbledon",
        "search for free stock photos for a landing page",
        "find compare the best noise cancelling headphones",
        "look up how to deploy Next.js on Vercel",
        "find latest unemployment statistics by state",
        "search for scholarships for computer science students",
        "look up international flight deals from NYC",
        "find best practices for API rate limiting",
        "search for case studies on AI in customer support",
    ],
    "web_analysis": [
        "analyze this webpage for SEO issues",
        "check the performance score of my website",
        "scan this landing page for conversion problems",
        "review the accessibility compliance of this site",
        "analyze the competitor pricing page structure",
        "check this page for broken links",
        "evaluate the UX of this checkout flow",
        "analyze the content strategy of hubspot.com",
        "check the mobile responsiveness of my site",
        "review the page load speed and suggest fixes",
        "analyze the meta tags on my product pages",
        "check if this site follows good schema markup",
        "compare the navigation structure of these two sites",
        "evaluate the CTA placement on this page",
        "analyze the readability of this blog post",
        "check the image alt text coverage on this page",
        "review the cookie consent implementation",
        "analyze the social proof elements on this homepage",
        "check the internal linking structure of this blog",
        "evaluate the trust signals on this ecommerce site",
        "analyze the font and color contrast accessibility",
        "review the site architecture for crawlability",
        "check the hreflang tags for international targeting",
        "analyze the content freshness across blog pages",
        "evaluate the video embedding strategy on this page",
        "check the structured data markup validity",
        "analyze the user engagement patterns on this site",
        "review the A/B test setup on this page",
        "compare the mobile vs desktop experience",
        "analyze the search functionality effectiveness",
    ],
    "research": [
        "research the market size for AI-powered tutoring",
        "deep dive into how retrieval augmented generation works",
        "investigate the competitive landscape of voice AI",
        "research best practices for building AI agents",
        "find out what frameworks are used for 3D web rendering",
        "investigate regulatory requirements for AI in finance",
        "research the history and evolution of large language models",
        "look into the environmental impact of training AI models",
        "investigate how competitor products handle data privacy",
        "research the latest advances in computer vision",
        "find out what makes a good AI training dataset",
        "investigate the technical architecture of Stripe payments",
        "research edge computing for real-time AI inference",
        "look into zero-knowledge proofs for identity verification",
        "research the technical requirements for building a search engine",
        "investigate how vector databases scale horizontally",
        "find out what technologies power real-time collaboration tools",
        "research the best approaches for anomaly detection in logs",
        "investigate the state of WebGPU adoption across browsers",
        "look into how Spotify discovers new music for recommendations",
        "research effective prompt engineering techniques for GPT models",
        "find out how autonomous vehicles process sensor data",
        "investigate the technical challenges of building a search engine",
        "research techniques for real-time speech translation",
        "look into how Netflix recommendation algorithm works technically",
        "research the security implications of running local AI models",
        "investigate how to build a privacy-preserving ML pipeline",
        "find out what makes vector search more effective than keyword search",
        "research the latest developments in robotic manipulation",
        "look into how autonomous drones navigate without GPS",
    ],
    "question_answering": [
        "what is the difference between REST and GraphQL",
        "explain how transformer attention mechanism works",
        "why does my Python script consume so much memory",
        "what are the best practices for securing API keys",
        "how does garbage collection work in Go",
        "what is the CAP theorem in distributed systems",
        "explain the difference between TCP and UDP",
        "why is my Docker container crashing on startup",
        "what are the SOLID principles in software design",
        "how does Kubernetes handle pod scheduling",
        "what is the difference between SQL and NoSQL databases",
        "explain how CORS works in web browsers",
        "why is async faster than sync in Python for IO",
        "what is the difference between horizontal and vertical scaling",
        "how does DNS resolution actually work step by step",
        "what are WebSockets and when should I use them",
        "explain the difference between authentication and authorization",
        "how does TLS encryption work at a high level",
        "what is eventual consistency in distributed databases",
        "explain the difference between layers and components in React",
        "how does a blockchain consensus mechanism work",
        "what is the difference between supervised and unsupervised learning",
        "explain how convolutional neural networks process images",
        "what are the tradeoffs between monorepo and polyrepo",
        "how does load balancing work in cloud infrastructure",
        "what is the difference between a process and a thread",
        "explain the CAP theorem and its practical implications",
        "how does rate limiting protect an API",
        "what are edge functions and when should I use them",
        "explain the difference between stateful and stateless services",
        "how does JWT token expiration work and how to refresh it",
        "what is the difference between containers and virtual machines",
        "explain how connection pooling improves database performance",
        "why is my React component re-rendering unnecessarily",
        "what is the observer pattern and when should I use it",
        "how does a reverse proxy improve security",
        "what is the difference between message queues and event streams",
        "explain the concept of eventual consistency with examples",
        "how does a Bloom filter reduce database lookups",
    ],
    "summarization": [
        "summarize this research paper about neural architecture search",
        "give me a TLDR of this 50-page technical document",
        "condense this meeting transcript into key action items",
        "summarize the main findings from these customer reviews",
        "create an executive summary of this quarterly report",
        "summarize the differences between these two proposals",
        "give me a brief overview of this codebase architecture",
        "summarize the competitive analysis from these articles",
        "condense this legal contract into plain English",
        "summarize the key arguments in this debate",
        "create a 3-sentence summary of this blog post series",
        "summarize the technical specs of this product comparison",
        "give me the highlights from this earnings call transcript",
        "summarize the user feedback from this survey data",
        "condense this API documentation into a quick reference",
        "summarize the pros and cons of these three solutions",
        "give me a one-paragraph summary of this whitepaper",
        "summarize the timeline of events from this investigation",
        "create a summary of the key metrics from this dashboard",
        "summarize the architecture decisions in this design doc",
        "condense this podcast episode into main talking points",
        "summarize the regulatory changes from this government report",
        "give me the key takeaways from this conference presentation",
        "summarize the differences between versions 2 and 3 of this library",
        "create a bullet-point summary of this security audit",
        "summarize the customer journey from this analytics data",
        "condense this technical RFC into its core proposal",
        "summarize the best practices from these industry reports",
        "give me a summary of the common themes in these bug reports",
        "summarize the performance benchmarks from this comparison",
    ],
    "code_generation": [
        "write a Python function to merge two sorted arrays",
        "generate a React component for a paginated data table",
        "write a SQL query to find the top 10 customers by revenue",
        "create a bash script to automate database backups",
        "write a TypeScript interface for a REST API response",
        "generate a Docker Compose file for a Node.js app with PostgreSQL",
        "write a Python async function for concurrent API calls",
        "create a Terraform config for an AWS Lambda function",
        "write a Python decorator for retrying failed operations",
        "generate a GitHub Actions workflow for CI/CD",
        "write a regex pattern to validate email addresses",
        "create a FastAPI endpoint for file upload with validation",
        "write a Python class implementing a least-recently-used cache",
        "generate a Kubernetes deployment manifest for a microservice",
        "write a Python script to convert CSV to JSON",
        "create a GraphQL schema for an e-commerce product catalog",
        "write a Python generator function for streaming large files",
        "generate unit tests for this authentication middleware",
        "write a Python dataclass for representing a binary tree node",
        "create a WebSocket server in Python using asyncio",
        "write a SQL migration to add a new column to users table",
        "generate a Python pipeline for data preprocessing",
        "write a React hook for debouncing search input",
        "create a Python context manager for database transactions",
        "write a bash script to rotate and compress log files",
        "generate a Python function that implements binary search",
        "create an Express.js middleware for request logging",
        "write a Python script to parallel download files from a URL list",
        "generate a React toast notification system with different severity levels",
        "write a Python class for managing a connection pool",
    ],
    "code_analysis": [
        "review this Python function for security vulnerabilities",
        "find the bug in this async JavaScript code",
        "analyze the time complexity of this sorting algorithm",
        "check this SQL query for performance issues",
        "review this pull request for code quality",
        "find potential race conditions in this concurrent code",
        "analyze the memory usage of this data processing pipeline",
        "review this API endpoint for input validation gaps",
        "check this code for proper error handling",
        "identify code smells in this module",
        "review this configuration for security best practices",
        "analyze the test coverage of this codebase",
        "check this Dockerfile for optimization opportunities",
        "review this database schema for normalization issues",
        "find potential null pointer exceptions in this code",
        "analyze the dependency graph of this project",
        "review this authentication flow for vulnerabilities",
        "check this regex for catastrophic backtracking risks",
        "analyze the coupling between these two modules",
        "review this error handling strategy for completeness",
        "check this API design for RESTful best practices",
        "analyze the scalability bottlenecks in this system design",
        "review this code for adherence to SOLID principles",
        "find hardcoded values that should be configurable",
        "analyze the logging strategy for observability gaps",
        "review this database migration for data loss risks",
        "check this encryption implementation for correctness",
        "analyze the thread safety of this shared state code",
        "review this deployment script for rollback safety",
        "identify deprecated API usage in this codebase",
        "check this build pipeline for security exposure",
        "analyze the resource leak potential in this file handler code",
        "review the error propagation in this middleware chain",
        "find potential injection vulnerabilities in this form handler",
        "analyze the caching strategy for invalidation correctness",
        "check this WebSocket implementation for connection leaks",
        "review the state management patterns in this React component",
        "identify N+1 query problems in this ORM usage",
        "analyze the event listener cleanup in this SPA lifecycle",
        "check this config for secrets that should be env vars",
        "review the rate limiting implementation for bypass vectors",
        "find memory leaks in this long-running background task",
        "analyze the retry logic for infinite loop potential",
        "check the idempotency guarantees of this webhook handler",
        "review this data serialization for deserialization vulnerabilities",
    ],
    "data_extraction": [
        "extract all email addresses from this webpage",
        "pull pricing information from this competitor site",
        "scrape job listings from this career page",
        "extract structured data from this news article",
        "pull all product names and prices from this catalog page",
        "extract contact information from this company directory",
        "scrape social media profiles from search results",
        "pull technical specifications from this product page",
        "extract key-value pairs from this configuration file",
        "scrape event dates and locations from this conference page",
        "extract all links and their anchor text from this page",
        "pull customer reviews and ratings from this product",
        "extract metadata from this set of images",
        "scrape real estate listings with price and location",
        "extract table data from this financial report PDF",
        "pull sentiment scores from these customer comments",
        "extract all hashtags and mentions from these posts",
        "scrape academic paper titles and abstracts from this search",
        "extract invoice line items from this document",
        "pull geolocation coordinates from this map embed",
        "extract phone numbers from this business directory",
        "scrape stock tickers and company names from this page",
        "extract structured FAQ data from this help center",
        "pull RSS feed entries and categorize them",
        "extract entity names from this legal document",
        "scrape authentication tokens from this API response",
        "extract color palettes from this design inspiration page",
        "pull version numbers and release dates from changelogs",
        "extract metadata from this database schema dump",
        "scrape product availability by store location",
    ],
    "recommendation": [
        "recommend a stack for building a real-time chat app",
        "suggest tools for monitoring production microservices",
        "what database should I use for a social network",
        "recommend a good book on system design interviews",
        "suggest alternatives to Firebase for a startup",
        "what ML framework is best for computer vision on edge",
        "recommend a project management tool for a small team",
        "suggest a CDN for serving images globally",
        "what authentication provider should I use for a SaaS",
        "recommend a monitoring stack for a Kubernetes cluster",
        "suggest a good approach for feature flags in production",
        "what BI tool is best for a 10-person data team",
        "recommend an email service for transactional emails",
        "suggest a CMS for a technical blog with code snippets",
        "what search engine should I integrate for an ecommerce site",
        "recommend a payment processor for international transactions",
        "suggest a design system for a B2B dashboard",
        "what testing framework works best for end-to-end tests",
        "recommend a deployment platform for a Python API",
        "suggest tools for building interactive data visualizations",
        "what caching strategy is best for a high-traffic API",
        "recommend a logging solution for distributed systems",
        "suggest a good GraphQL client for a React app",
        "what CI/CD pipeline is best for a monorepo",
        "recommend a video conferencing SDK for embedding",
        "suggest a text editor component for a code playground",
        "what AI model is best for generating SQL from natural language",
        "recommend a chatbot framework for customer support",
        "suggest tools for A/B testing in a web application",
        "what approach should I use for real-time notifications",
    ],
    "classification": [
        "classify this customer support ticket by urgency",
        "categorize these articles by topic",
        "sort these emails by priority level",
        "label these images as safe or unsafe content",
        "classify this code snippet by programming language",
        "categorize these products by type and price range",
        "determine the sentiment of these reviews",
        "sort these support tickets by department",
        "classify this document as technical or business",
        "categorize these leads by funnel stage",
        "label these bug reports by severity",
        "classify this text as formal or informal",
        "sort these candidates by skill match level",
        "categorize these data points by anomaly type",
        "classify these user actions as high or low intent",
        "label these tweets as relevant or not relevant to our brand",
        "categorize these tasks by estimated effort",
        "classify this query by language",
        "sort these articles by publication date and relevance",
        "categorize these metrics by dashboard section",
        "classify these network events as normal or suspicious",
        "label these commits as feature, fix, or refactor",
        "categorize these customers by engagement level",
        "classify these contracts by risk level",
        "sort these research papers by methodology type",
        "categorize these API endpoints by version and status",
        "label these design mockups as approved or pending",
        "classify these user feedback items by theme",
        "sort these pricing plans by feature tier",
        "categorize these datasets by domain and format",
    ],
    "navigation": [
        "open the lead dashboard",
        "go to the settings page",
        "navigate to the billing section",
        "take me to the analytics overview",
        "open the team management panel",
        "go to the API documentation",
        "navigate to the workflow editor",
        "open the file manager",
        "go to the integrations page",
        "take me to the user profile settings",
        "open the notifications center",
        "go to the project overview page",
        "navigate to the search results",
        "open the terminal or console",
        "go to the deployment dashboard",
        "take me to the audit log",
        "open the knowledge base",
        "go to the conversation history",
        "navigate to the model selection screen",
        "open the code editor",
        "go back to the previous page",
        "navigate to the reporting section",
        "open the voice command interface",
        "go to the credential manager",
        "take me to the activity feed",
        "open the batch operations panel",
        "go to the sandbox environment",
        "navigate to the schema editor",
        "open the realtime monitor",
        "go to the backup management page",
        "open the subscription management panel",
        "navigate to the user roles and permissions",
        "go to the notification preferences",
        "take me to the data export page",
        "open the custom fields editor",
        "go to the webhook configuration",
        "navigate to the email templates section",
        "open the brand and theme settings",
        "go to the API key management page",
    ],
    "voice_command": [
        "start listening",
        "stop recording",
        "repeat that",
        "speak slower please",
        "change the voice to a male voice",
        "increase the speaking volume",
        "pause the audio playback",
        "resume the voice assistant",
        "switch to voice mode",
        "can you whisper instead",
        "use a more natural voice",
        "mute the microphone",
        "unmute the microphone",
        "set the language to Spanish",
        "switch back to English",
        "enable noise cancellation",
        "read this text out loud",
        "read the last message aloud",
        "lower the speech rate",
        "change TTS engine to ElevenLabs",
        "use a child-friendly voice",
        "enable real-time transcription",
        "set the wake word sensitivity higher",
        "disable hands-free mode",
        "start voice dictation",
        "stop voice dictation",
        "use push-to-talk mode",
        "activate ambient listening",
        "change the pronunciation of my name",
        "enable speech-to-text logging",
        "speak up I cannot hear you",
        "turn on closed captions",
        "change the voice speed to 1.5x",
        "slow down the reading speed",
        "fast forward the audio by 10 seconds",
        "rewind the last 5 seconds",
        "skip to the next section",
        "repeat the last sentence",
        "change the audio output to Bluetooth",
        "route audio to speaker instead of headphones",
        "set the audio quality to high",
        "enable voice feedback after each command",
        "turn off voice responses",
        "make the assistant speak in a whisper",
        "enable simultaneous translation mode",
        "set voice pitch to medium",
        "change the assistant voice to a British accent",
        "enable wake word detection",
        "set the listening timeout to 30 seconds",
        "use a deeper voice",
        "play the audio in reverse",
        "lower the microphone sensitivity",
        "boost the microphone gain",
        "enable automatic punctuation in transcription",
        "switch to continuous listening mode",
        "enable the haptic feedback on voice activation",
        "set the voice gender to non-binary",
        "enable echo cancellation during calls",
        "calibrate the microphone for my room",
        "switch to the neural TTS model",
        "enable speaker identification in recordings",
        "set the transcription language to auto-detect",
        "turn on voice-activated music playback",
        "disable the wake word sound",
        "enable barge-in so I can interrupt the assistant",
        "set the maximum recording duration to 60 seconds",
        "switch to offline voice recognition mode",
        "enable sentiment detection in voice input",
        "set the voice assistant personality to professional",
    ],
    "automation": [
        "set up a daily briefing at 8am",
        "automate sending weekly reports to the team",
        "create a webhook to trigger on new signups",
        "automatically tag incoming leads by source",
        "set up alerts when response time exceeds 5 seconds",
        "automate the backup of my database every night",
        "create a bot that answers common questions",
        "set up automatic deployment on merge to main",
        "automate data sync between Salesforce and our DB",
        "create a cron job that checks website uptime",
        "automate sending welcome emails to new users",
        "set up automatic scaling based on CPU usage",
        "create a workflow that summarizes daily Slack messages",
        "automate the process of extracting data from PDFs",
        "set up automatic model retraining on new data",
        "create a bot that monitors competitor pricing",
        "automate the generation of monthly invoices",
        "set up alerts for unusual login patterns",
        "automate cross-posting content to multiple platforms",
        "create a pipeline that processes uploaded documents",
        "automate the creation of JIRA tickets from emails",
        "set up automatic image optimization on upload",
        "automate the process of matching resumes to job descriptions",
        "create a workflow that notifies on failed API calls",
        "automate the cleanup of expired sessions",
        "set up automatic A/B test result analysis",
        "create a pipeline that enriches lead data from multiple sources",
        "automate the process of generating test data",
        "set up a watchdog that restarts crashed services",
        "automate the compilation of weekly metrics dashboards",
        "auto-assign support tickets based on agent expertise",
        "set up automatic retry for failed payment processing",
        "create a bot that posts daily standup summaries to Slack",
        "automate the process of deduplicating CRM contacts",
        "set up nightly database migration backups",
        "automatically generate changelogs from git commits",
        "create a workflow that validates email deliverability",
        "set up auto-scaling for the ML inference pipeline",
        "automate the weekly generation of compliance reports",
        "create a bot that monitors SSL certificate expiration",
        "set up automatic log rotation and archival",
        "automate the generation of test fixtures from production data",
        "create a workflow that syncs inventory across platforms",
        "set up alerts when API rate limits are approaching",
        "automate the approval workflow for high-value purchases",
        "create a pipeline that detects and blocks spam signups",
        "set up automatic SSL certificate renewal",
        "automate the process of tagging support tickets by language",
        "create a bot that monitors competitor blog for new posts",
        "set up automatic conversion tracking across ad platforms",
        "automate the deletion of orphaned cloud storage objects",
        "create a workflow that routes customer feedback to product",
        "set up automatic resource cleanup for idle dev environments",
        "automate the process of collecting NPS survey responses",
        "create a pipeline that deduplicates analytics events",
        "set up automatic notification when deployments fail",
        "automate the generation of API usage reports for clients",
        "create a workflow that enriches job postings with salary data",
        "automate the nightly aggregation of security scan results",
    ],
    "workflow_creation": [
        "build a lead qualification pipeline",
        "create a content moderation workflow",
        "design an onboarding automation sequence",
        "build a customer feedback collection process",
        "create a document review and approval workflow",
        "design a multi-step form with conditional logic",
        "build a data validation and cleaning pipeline",
        "create an employee referral tracking workflow",
        "design a helpdesk ticket routing system",
        "build a social media content scheduling workflow",
        "create a quality assurance testing pipeline",
        "design a vendor evaluation and selection process",
        "build a customer onboarding email sequence",
        "create a content creation pipeline from research to publish",
        "design a sales pipeline from lead to close",
        "build a data integration pipeline from multiple sources",
        "create an incident response workflow",
        "design a product feedback collection and categorization process",
        "build a KYC verification workflow",
        "create a content repurposing pipeline across channels",
        "design a customer health scoring system",
        "build an automated reporting workflow",
        "create a developer onboarding checklist workflow",
        "design a competitive monitoring intelligence pipeline",
        "build a contract review and approval workflow",
        "create a multi-model AI inference pipeline",
        "design a user engagement scoring workflow",
        "build a data governance compliance workflow",
        "create a knowledge base auto-population process",
        "design a cross-team collaboration workflow",
    ],
    "workflow_modification": [
        "add a confirmation step to the deployment workflow",
        "modify the lead scoring criteria in the pipeline",
        "update the email template in the onboarding sequence",
        "remove the manual approval step from the invoice process",
        "change the trigger condition for the alert workflow",
        "add error handling to the data sync pipeline",
        "modify the routing rules for support tickets",
        "update the schedule for the daily briefing automation",
        "add a new notification channel to the alert system",
        "change the retention policy in the cleanup workflow",
        "modify the classification rules in the content moderator",
        "update the webhook endpoint in the integration workflow",
        "add retry logic to the API call automation",
        "change the priority calculation in the triage workflow",
        "update the data validation rules in the intake pipeline",
        "add a feedback loop to the recommendation engine",
        "modify the escalation path in the incident workflow",
        "update the throttling limits in the rate limiter",
        "change the deduplication logic in the data pipeline",
        "add a new step to the contract review workflow",
        "modify the A/B test assignment logic",
        "update the caching strategy in the content delivery workflow",
        "change the aggregation window in the analytics pipeline",
        "add logging to the background job processor",
        "modify the consent capture in the data collection workflow",
        "update the fallback behavior in the voice command handler",
        "change the batch size in the data processing pipeline",
        "add a pre-check to the deployment automation",
        "modify the scoring weights in the lead ranking system",
        "update the timeout values in the async workflow executor",
    ],
    "analytics": [
        "show me the conversion rate for this month",
        "what is the average response time for our API",
        "give me a breakdown of traffic sources this week",
        "how many leads did we generate this quarter",
        "what is the churn rate for our SaaS product",
        "show the daily active users trend over the past 30 days",
        "what is the cost per acquisition for each marketing channel",
        "give me the revenue breakdown by product line",
        "how does our page load time compare to competitors",
        "what is the employee attrition rate this year",
        "show the cohort retention analysis for new users",
        "what percentage of support tickets are resolved within 24 hours",
        "give me the pipeline velocity metrics for the sales team",
        "how many API calls are we making per day",
        "what is the error rate across our microservices",
        "show the geographic distribution of our user base",
        "what is the average session duration on our app",
        "give me the breakdown of feature usage across the platform",
        "how many new customers did we acquire this month",
        "what is the lifetime value of a typical customer",
        "show the distribution of support ticket categories",
        "what is the average deal size in our sales pipeline",
        "give me the time series of database query performance",
        "how does our content engagement compare across channels",
        "what is the ratio of organic vs paid traffic",
        "show the progression of our OKR progress this quarter",
        "what percentage of our users are on the free vs paid plan",
        "give me the month-over-month growth in key metrics",
        "how many experiments are currently running in production",
        "what is the infrastructure cost per user",
    ],
    "general_chat": [
        "hello how are you doing today",
        "what can you help me with",
        "tell me a joke",
        "thanks for your help",
        "that was really useful",
        "can you explain what you just did",
        "how does this work",
        "that is amazing",
        "I need a break",
        "what do you think about AI",
        "tell me about yourself",
        "what are your capabilities",
        "that is not what I meant",
        "let me try something different",
        "can you do that again more slowly",
        "this is really cool",
        "I appreciate your help",
        "nice work on that",
        "you are very helpful",
        "have a great day",
        "what is your favorite programming language",
        "do you enjoy helping people",
        "that is a great suggestion",
        "I learned something new today",
        "you made my day easier",
        "keep up the good work",
        "that solved my problem",
        "wow I did not expect that",
        "you are really smart",
        "thank you so much",
        "that is fascinating tell me more",
        "I disagree with that approach",
        "can you give me an analogy for that",
        "what would you do if you were human",
        "do you dream at night",
        "are you sentient",
        "what is the meaning of consciousness",
        "can you be creative",
        "do you have feelings",
        "tell me something surprising",
        "that is a weird question I know",
        "you are being very patient with me",
        "I like the way you think",
        "can we be friends",
        "you remind me of someone",
        "that is a bold claim",
        "I am not sure I agree",
        "prove it",
        "show me the evidence",
    ],
    "unknown": [
        "asdfghjkl",
        "123456789",
        "can you translate this painting",
        "make the color more blueish",
        "order me a pizza",
        "book a flight to Mars",
        "hack into this server",
        "write me a haiku about potatoes",
        "what is the meaning of life the universe and everything",
        "do a barrel roll",
        "banana phone ring ring",
        "flip a coin for me",
        "random number between 1 and 100",
        "set a timer for 5 minutes",
        "call my mother",
        "what is 0 divided by 0",
        "tell me the future",
        "read my mind",
        "turn off the sun",
        "make me invisible",
        "water my plants",
        "feed my cat",
        "fold my laundry",
        "build me a spaceship",
        "invent a new color",
        "solve world hunger",
        "explain the taste of the color blue",
        "what does the fox say",
        "speak whale",
        "decode this emoji sequence",
        "sharpen my pencil",
        "rewind time by 5 minutes",
        "make the gravity weaker",
        "teleport me to the kitchen",
        "count the stars in the sky",
        "make it snow inside my house",
        "translate this into dolphin language",
        "time travel to 1999",
        "make me taller by 3 inches",
        "calculate the meaning of pi to the last digit",
        "find the lost city of Atlantis",
        "draw a map of Middle Earth",
        "make my coffee taste like chocolate",
        "bring me a unicorn",
        "teach my dog to speak French",
        "grow a tree in my office",
        "make this conversation disappear",
        "fix my broken shoelace remotely",
        "remove Mondays from the calendar",
        "make the internet taste like strawberries",
        "concatenate two rainbows",
        "debug my dreams",
        "compile my feelings into an executable",
        "deploy my anxiety to production",
        "git commit -m fix my life",
        "rm -rf my responsibilities",
        "sudo make me a sandwich",
        "echo hello world inside a black hole",
        "npm install happiness",
        "pip install motivation",
        "docker compose up my motivation",
        "kubectl scale my ambitions to 100 replicas",
        "terraform apply world peace",
        "git blame for my bad decisions",
        "cron job to make me eat healthier",
        "ssh into my imagination",
        "curl the universe for answers",
    ],
}


def main() -> int:
    out = Path("services/ml-service/datasets/raw/intents.generated.jsonl")
    out.parent.mkdir(parents=True, exist_ok=True)
    rng = random.Random(42)
    lines: list[str] = []
    for intent, queries in QUERIES.items():
        for q in queries:
            lines.append(json.dumps({"text": q.strip(), "intent": intent}))
    rng.shuffle(lines)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(lines)} queries across {len(QUERIES)} intents -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
